"""
Major journals by discipline for LiterView.
Auto-generated by sync_journals.py
"""

# OpenAlex Source ID -> Journal Name
# ISSN stored in comments for Crossref fallback

JOURNALS_BY_DISCIPLINE = {
    # =========================================================================
    # ENGINEERING
    # =========================================================================

    "civil-engineering": {
        "S145524021": "Advances in Water Resources",
        "S172073041": "Automation in Construction",
        "S56464651": "Building and Environment",
        "S105963835": "Canadian Geotechnical Journal",
        "S123887920": "Cement and Concrete Composites",
        "S186020892": "Cement and Concrete Research",
        "S29980478": "Construction and Building Materials",
        "S194562448": "Earthquake Engineering & Structural Dynamics",
        "S117562080": "Earthquake Spectra",
        "S6846437": "Energy and Buildings",
        "S165454098": "Engineering Structures",
        "S170199316": "Géotechnique",
        "S176637136": "Journal of Computing in Civil Engineering",
        "S2764777209": "Journal of Construction Engineering and Management",
        "S178493899": "Journal of Geotechnical and Geoenvironmental Engineering",
        "S92829914": "Journal of Hydraulic Engineering",
        "S55737203": "Journal of Hydrology",
        "S54853311": "Journal of Infrastructure Systems",
        "S93312259": "Journal of Structural Engineering",
        "S4210194109": "Journal of Transportation Engineering",
        "S70708404": "Natural Hazards and Earth System Sciences",
        "S99356198": "Soil Dynamics and Earthquake Engineering",
        "S164417264": "Soils and Foundations",
        "S1507157": "Structural Safety",
        "S130252234": "Transportation Science",
        "S204847658": "Water Resources Research",
    },

    "computer-science": {
        "S157921468": "ACM Computing Surveys",
        "S4363608767": "ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
        "S89276529": "ACM Transactions on Computer-Human Interaction",
        "S90119964": "ACM Transactions on Database Systems",
        "S185367456": "ACM Transactions on Graphics",
        "S4394735545": "ACM Transactions on Information Systems",  # ISSN: 1046-8188
        "S41449414": "ACM Transactions on Programming Languages and Systems",  # ISSN: 0164-0925
        "S4393916742": "Advances in Neural Information Processing Systems",
        "S4363608652": "Annual Meeting of the Association for Computational Linguistics",
        "S196139623": "Artificial Intelligence",
        "S122814990": "Artificial Intelligence Review",  # ISSN: 0269-2821
        "S103482838": "Communications of the ACM",
        "S155526855": "Computational Linguistics",  # ISSN: 0891-2017
        "S185008460": "Computer Vision and Image Understanding",  # ISSN: 1077-3142
        "S121920818": "Data Mining and Knowledge Discovery",  # ISSN: 1384-5810
        "S13144211": "Expert Systems with Applications",  # ISSN: 0957-4174
        "S4210188176": "Foundations and Trends in Machine Learning",
        "S157670870": "IEEE Transactions on Computers",  # ISSN: 0018-9340
        "S133795288": "IEEE Transactions on Dependable and Secure Computing",  # ISSN: 1545-5971
        "S4210173141": "IEEE Transactions on Image Processing",  # ISSN: 1057-7149
        "S4502562": "IEEE Transactions on Information Theory",
        "S30698027": "IEEE Transactions on Knowledge and Data Engineering",
        "S69141925": "IEEE Transactions on Mobile Computing",  # ISSN: 1536-1233
        "S4210175523": "IEEE Transactions on Neural Networks and Learning Systems",
        "S97130795": "IEEE Transactions on Parallel and Distributed Systems",
        "S199944782": "IEEE Transactions on Pattern Analysis and Machine Intelligence",
        "S8351582": "IEEE Transactions on Software Engineering",
        "S84775595": "IEEE Transactions on Visualization and Computer Graphics",
        "S4363608749": "IEEE/CVF Conference on Computer Vision and Pattern Recognition",
        "S193006928": "Information Systems",  # ISSN: 0306-4379
        "S4306419637": "International Conference on Learning Representations",
        "S25538012": "International Journal of Computer Vision",  # ISSN: 0920-5691
        "S139930977": "Journal of Artificial Intelligence Research",
        "S118988714": "Journal of Machine Learning Research",
        "S118992489": "Journal of the ACM",
        "S10169007": "Knowledge-Based Systems",  # ISSN: 0950-7051
        "S62148650": "Machine Learning",
        "S2912241403": "Nature Machine Intelligence",
        "S207023548": "Neural Computation",
        "S123019304": "Neural Networks",  # ISSN: 0893-6080
        "S45693802": "Neurocomputing",  # ISSN: 0925-2312
        "S414566": "Pattern Recognition",  # ISSN: 0031-3203
        "S4210227020": "Proceedings of the International Conference on Machine Learning",
        "S153560523": "SIAM Journal on Computing",
        "S78926909": "The VLDB Journal",
        "S2729999759": "Transactions of the Association for Computational Linguistics",  # ISSN: 2307-387X
    },

    "electrical-engineering": {
        "S51360982": "Automatica",
        "S105928092": "Control Engineering Practice",
        "S149016011": "Electronics Letters",  # ISSN: 0013-5194
        "S2485537415": "IEEE Access",
        "S158797327": "IEEE Communications Magazine",
        "S83637746": "IEEE Journal of Solid-State Circuits",
        "S90422530": "IEEE Journal on Selected Areas in Communications",
        "S189694085": "IEEE Sensors Journal",
        "S85738991": "IEEE Transactions on Antennas and Propagation",
        "S184954342": "IEEE Transactions on Automatic Control",
        "S116977442": "IEEE Transactions on Circuits and Systems I",  # ISSN: 1549-8328
        "S81140365": "IEEE Transactions on Circuits and Systems II",  # ISSN: 1057-7130
        "S196647941": "IEEE Transactions on Communications",
        "S133363738": "IEEE Transactions on Control Systems Technology",
        "S163644703": "IEEE Transactions on Electromagnetic Compatibility",
        "S162355128": "IEEE Transactions on Electron Devices",
        "S64770346": "IEEE Transactions on Energy Conversion",
        "S58031724": "IEEE Transactions on Industrial Electronics",
        "S10892749": "IEEE Transactions on Instrumentation and Measurement",
        "S198879913": "IEEE Transactions on Microwave Theory and Techniques",
        "S29875816": "IEEE Transactions on Power Electronics",
        "S201921491": "IEEE Transactions on Power Systems",
        "S144620930": "IEEE Transactions on Robotics",
        "S168680287": "IEEE Transactions on Signal Processing",
        "S59604973": "IEEE Transactions on Smart Grid",
        "S63459445": "IEEE Transactions on Wireless Communications",
        "S13961689": "IEEE/ASME Transactions on Mechatronics",
        "S96000363": "Journal of Process Control",
        "S154637859": "Signal Processing",
    },

    "materials-science": {
        "S164001016": "ACS Applied Materials & Interfaces",
        "S64016596": "Acta Materialia",
        "S99352657": "Advanced Materials",
        "S163807576": "Biomaterials",
        "S96167972": "Corrosion Science",
        "S38855548": "Intermetallics",
        "S10186584": "International Journal of Plasticity",
        "S67716761": "Journal of Alloys and Compounds",
        "S184573928": "Journal of Biomedical Materials Research Part A",
        "S26125866": "Journal of Materials Science",
        "S53162366": "Journal of the American Ceramic Society",
        "S158447136": "Journal of the European Ceramic Society",
        "S105775785": "Journal of the Mechanics and Physics of Solids",
        "S177196338": "Macromolecules",
        "S53842986": "Materials Characterization",
        "S63322718": "Materials Today",
        "S176710131": "Mechanics of Materials",
        "S165830345": "Metallurgical and Materials Transactions A",
        "S68503223": "Metallurgical and Materials Transactions B",
        "S143846845": "Nano Letters",
        "S23181512": "Nanoscale",
        "S103895331": "Nature Materials",
        "S186054908": "Polymer",
        "S88404446": "Progress in Materials Science",
        "S105962883": "Scripta Materialia",
        "S94619837": "Small",
        "S76010543": "Surface and Coatings Technology",
        "S84339699": "Thin Solid Films",
    },

    "mechanical-engineering": {
        "S141152059": "Annals of Biomedical Engineering",
        "S129676613": "Applied Thermal Engineering",
        "S2898225552": "CIRP Annals",
        "S52363224": "Composite Structures",
        "S52442148": "Composites Science and Technology",
        "S40006715": "Computer Methods in Applied Mechanics and Engineering",
        "S111482492": "Computers & Structures",
        "S17983605": "Engineering Fracture Mechanics",
        "S145843112": "Finite Elements in Analysis and Design",
        "S165651092": "International Journal for Numerical Methods in Engineering",
        "S71623918": "International Journal of Fatigue",
        "S90999920": "International Journal of Heat and Mass Transfer",
        "S154368109": "International Journal of Machine Tools and Manufacture",
        "S72716621": "International Journal of Mechanical Sciences",
        "S128740003": "International Journal of Thermal Sciences",
        "S124014869": "Journal of Applied Mechanics",
        "S4210187999": "Journal of Biomechanical Engineering",
        "S152000018": "Journal of Fluid Mechanics",
        "S4210206986": "Journal of Heat Transfer",
        "S193263997": "Journal of Manufacturing Science and Engineering",
        "S88457320": "Journal of Mechanical Design",
        "S99182027": "Journal of Sound and Vibration",
        "S4210169712": "Journal of Tribology",
        "S31534900": "Journal of Vibration and Acoustics",
        "S128368299": "Mechanical Systems and Signal Processing",
        "S6785741": "Mechanism and Machine Theory",
        "S47380182": "Mechatronics",
        "S22862804": "Physics of Fluids",
        "S24284137": "Tribology International",
        "S16737290": "Wear",
    },


    # =========================================================================
    # FORMAL SCIENCES
    # =========================================================================

    "logic": {
        "S172477885": "Annals of Pure and Applied Logic",
        "S188076996": "Archive for Mathematical Logic",
        "S130801046": "Bulletin of Symbolic Logic",
        "S93117276": "History and Philosophy of Logic",
        "S164898596": "Journal of Applied Logic",
        "S47057106": "Journal of Logic and Computation",
        "S29890666": "Journal of Mathematical Logic",
        "S161120620": "Journal of Philosophical Logic",
        "S177675236": "Journal of Symbolic Logic",
        "S172351290": "Mathematical Logic Quarterly",
        "S78544662": "Notre Dame Journal of Formal Logic",
        "S30880287": "Studia Logica",
        "S255146": "Synthese",
    },

    "mathematics": {
        "S113542759": "Acta Mathematica",
        "S122441808": "Advances in Mathematics",
        "S45918994": "Annals of Mathematics",
        "S40212770": "Annals of Probability",
        "S100601982": "Communications in Mathematical Physics",
        "S134818455": "Communications on Pure and Applied Mathematics",
        "S171170845": "Duke Mathematical Journal",
        "S84214272": "Geometric and Functional Analysis",
        "S4306402194": "Inventiones Mathematicae",
        "S184147796": "Journal of Algebra",
        "S23326474": "Journal of Differential Geometry",
        "S130224168": "Journal of the American Mathematical Society",
        "S192217950": "Mathematische Annalen",
        "S105693234": "Probability Theory and Related Fields",
        "S4210226894": "Proceedings of the American Mathematical Society",
        "S77200987": "SIAM Journal on Applied Mathematics",
        "S160107561": "SIAM Review",
        "S182850260": "Stochastic Processes and their Applications",
        "S60030702": "Transactions of the American Mathematical Society",
    },

    "statistics": {
        "S112778392": "Annals of Applied Statistics",
        "S40212770": "Annals of Probability",
        "S119757635": "Annals of Statistics",
        "S127898559": "Bayesian Analysis",
        "S172180718": "Biometrika",
        "S190140075": "Biostatistics",
        "S76159266": "Journal of Computational and Graphical Statistics",
        "S127742747": "Journal of Econometrics",
        "S167961193": "Journal of Statistical Software",
        "S4394736638": "Journal of the American Statistical Association",
        "S145009937": "Journal of the Royal Statistical Society Series B",
        "S23408671": "Statistica Sinica",
        "S12967704": "Statistical Science",
        "S5437875": "Statistics and Computing",
        "S55189604": "Statistics in Medicine",
        "S985303": "Technometrics",
    },


    # =========================================================================
    # HEALTH SCIENCES
    # =========================================================================

    "medicine": {
        "S119722071": "Annals of Internal Medicine",
        "S192814187": "BMJ",
        "S116251202": "Circulation",
        "S129060628": "Diabetes",
        "S49878492": "Diabetes Care",
        "S181568219": "European Heart Journal",
        "S143352558": "Gastroenterology",
        "S3251770": "Gut",
        "S172573765": "JAMA",
        "S2765015654": "JAMA Cardiology",
        "S65364685": "JAMA Internal Medicine",
        "S164389565": "JAMA Neurology",
        "S2756165422": "JAMA Oncology",
        "S14226812": "JAMA Pediatrics",
        "S2495708506": "JAMA Psychiatry",
        "S114430552": "Journal of Clinical Investigation",
        "S15137598": "Journal of Clinical Oncology",
        "S203256638": "Nature Medicine",
        "S62468778": "New England Journal of Medicine",
        "S49861241": "The Lancet",
        "S4210176958": "The Lancet Global Health",
        "S23772524": "The Lancet Infectious Diseases",
        "S70053155": "The Lancet Neurology",
        "S116900674": "The Lancet Oncology",
        "S2531556786": "The Lancet Psychiatry",
    },

    "nursing": {
        "S22017307": "Advances in Nursing Science",
        "S144851420": "Applied Nursing Research",
        "S153670922": "Clinical Nursing Research",
        "S56493663": "International Journal of Nursing Studies",
        "S137832324": "Journal of Advanced Nursing",
        "S180106345": "Journal of Clinical Nursing",
        "S152990921": "Journal of Nursing Education",
        "S172540258": "Journal of Nursing Management",
        "S205285807": "Journal of Nursing Scholarship",
        "S162826810": "Journal of Professional Nursing",
        "S62565178": "Nurse Education Today",
        "S139566883": "Nurse Education in Practice",
        "S150985620": "Nursing Ethics",
        "S163228481": "Nursing Outlook",
        "S57227388": "Nursing Research",
        "S95299427": "Nursing Science Quarterly",
        "S138039743": "Research in Nursing & Health",
        "S83825622": "Western Journal of Nursing Research",
        "S205870262": "Worldviews on Evidence-Based Nursing",
    },

    "pharmacology": {
        "S191852912": "ACS Medicinal Chemistry Letters",
        "S185534594": "Biochemical Pharmacology",
        "S10422866": "Bioorganic & Medicinal Chemistry",
        "S30970080": "Bioorganic & Medicinal Chemistry Letters",
        "S13842274": "British Journal of Clinical Pharmacology",
        "S55107261": "British Journal of Pharmacology",
        "S136164820": "ChemMedChem",
        "S69290020": "Clinical Pharmacokinetics",
        "S159852663": "Clinical Pharmacology & Therapeutics",
        "S152068293": "Drug Discovery Today",
        "S145039780": "Drug Metabolism and Disposition",
        "S119477091": "European Journal of Pharmaceutical Sciences",
        "S187816532": "European Journal of Pharmacology",
        "S131016564": "International Journal of Pharmaceutics",
        "S161954266": "Journal of Controlled Release",
        "S162030435": "Journal of Medicinal Chemistry",
        "S102125482": "Journal of Pharmacology and Experimental Therapeutics",
        "S62949411": "Molecular Pharmacology",
        "S186543748": "Nature Reviews Drug Discovery",
        "S160566677": "Neuropharmacology",
        "S103865650": "Pharmaceutical Research",
        "S161680845": "Pharmacological Reviews",
        "S31167473": "Trends in Pharmacological Sciences",
        "S48760969": "Xenobiotica",
    },

    "public-health": {
        "S170967050": "American Journal of Epidemiology",
        "S168049282": "American Journal of Public Health",
        "S40844199": "Annals of Epidemiology",
        "S200437886": "BMC Public Health",
        "S4210185023": "Health Affairs",
        "S13389975": "International Journal of Epidemiology",
        "S166621295": "Journal of Health Economics",
        "S2764808104": "Lancet Public Health",
        "S4210194528": "Lancet Regional Health - Americas",
        "S1650206": "Milbank Quarterly",
        "S8081180": "Preventive Medicine",
        "S106822843": "Social Science & Medicine",
    },


    # =========================================================================
    # HUMANITIES
    # =========================================================================

    "art-history": {
        "S29163172": "American Art",
        "S173069353": "Art Bulletin",  # ISSN: 0004-3079
        "S56668943": "Art History",
        "S184725536": "Art Journal",
        "S54922319": "Artforum",  # ISSN: 1086-7058
        "S158461301": "Burlington Magazine",  # ISSN: 0007-6287
        "S175526339": "Grey Room",
        "S74450657": "History of Photography",
        "S43804791": "Journal of Visual Culture",
        "S99631028": "Journal of the Warburg and Courtauld Institutes",
        "S185926442": "Modernism/modernity",
        "S16663008": "Museum Management and Curatorship",
        "S4210167961": "Nineteenth-Century Art Worldwide",
        "S142871922": "October",
        "S19496192": "Oxford Art Journal",
        "S20903574": "Photography and Culture",
        "S193779622": "Renaissance Quarterly",
        "S152428769": "Visual Studies",
        "S35820829": "Winterthur Portfolio",
        "S135064885": "Zeitschrift für Kunstgeschichte",  # ISSN: 0044-2992
    },

    "history": {
        "S197437610": "American Historical Review",
        "S71642434": "Bulletin of the History of Medicine",  # ISSN: 0007-5140
        "S88020226": "Business History Review",
        "S198731068": "Central European History",
        "S42018803": "Civil War History",  # ISSN: 0009-8078
        "S21304105": "Comparative Studies in Society and History",
        "S154084123": "Diplomatic History",  # ISSN: 0145-2096
        "S165492527": "Economic History Review",
        "S76796937": "Environmental History",
        "S190412762": "French Historical Studies",
        "S92608454": "History and Theory",
        "S55001385": "History of Science",  # ISSN: 0073-2753
        "S452692": "Holocaust and Genocide Studies",  # ISSN: 1476-7937
        "S120387555": "International History Review",  # ISSN: 0707-5332
        "S192525298": "Isis",  # ISSN: 0021-1753
        "S3091228": "Journal of African History",
        "S95667342": "Journal of American History",
        "S114691300": "Journal of Asian Studies",
        "S197577296": "Journal of British Studies",
        "S161550498": "Journal of Contemporary History",  # ISSN: 0022-0094
        "S122073985": "Journal of Economic History",
        "S171627239": "Journal of Global History",  # ISSN: 1740-0228
        "S181027741": "Journal of Interdisciplinary History",
        "S169672611": "Journal of Latin American Studies",
        "S70122655": "Journal of Medieval History",  # ISSN: 0304-4181
        "S125270255": "Journal of Modern History",
        "S74845278": "Journal of Social History",
        "S119035484": "Journal of Southern History",  # ISSN: 0022-4642
        "S19713811": "Journal of Urban History",
        "S52423121": "Journal of World History",
        "S7010830": "Journal of the Early Republic",  # ISSN: 0275-1275
        "S34788281": "Journal of the History of Ideas",
        "S107525555": "Journal of the History of Medicine and Allied Sciences",  # ISSN: 0022-5045
        "S176330965": "Labor History",
        "S42922845": "Past & Present",
        "S193779622": "Renaissance Quarterly",
        "S3127539": "Slavic Review",
        "S145330833": "Technology and Culture",  # ISSN: 0040-165X
        "S86102577": "William and Mary Quarterly",  # ISSN: 0043-5597
    },

    "law": {
        "S17212635": "American Criminal Law Review",  # ISSN: 0164-0364
        "S167039476": "American Journal of Comparative Law",  # ISSN: 0002-919X
        "S160097506": "American Journal of International Law",
        "S85562951": "Boston University Law Review",  # ISSN: 0006-8047
        "S172107878": "California Law Review",
        "S183770981": "Columbia Law Review",
        "S194663980": "Cornell Law Review",  # ISSN: 0010-8847
        "S56047584": "Criminal Law and Philosophy",
        "S120433428": "Duke Law Journal",
        "S175405714": "European Journal of International Law",
        "S54227673": "Georgetown Law Journal",  # ISSN: 0016-8092
        "S1110361": "Harvard Journal of Law & Public Policy",
        "S117766065": "Harvard Law Review",
        "S7938327": "International Journal of Constitutional Law",
        "S66810094": "Journal of Criminal Law and Criminology",  # ISSN: 0091-4169
        "S124682778": "Journal of Empirical Legal Studies",
        "S4387283559": "Journal of Law and Economics",  # ISSN: 2963-7937
        "S2735206538": "Journal of Legal Analysis",  # ISSN: 1946-5319
        "S9231424": "Journal of Legal Studies",
        "S44706263": "Law & Society Review",
        "S153292947": "Law and Philosophy",  # ISSN: 0167-5249
        "S139242520": "Legal Theory",  # ISSN: 1352-3252
        "S69429964": "Michigan Law Review",
        "S120024774": "Minnesota Law Review",  # ISSN: 0026-5535
        "S82119083": "Modern Law Review",  # ISSN: 0026-7961
        "S15963141": "Northwestern University Law Review",
        "S34110867": "Oxford Journal of Legal Studies",  # ISSN: 0143-6503
        "S161743634": "Stanford Law Review",
        "S94195887": "Supreme Court Review",
        "S105204244": "Texas Law Review",
        "S21339052": "University of Chicago Law Review",  # ISSN: 0041-9494
        "S107914479": "University of Pennsylvania Law Review",
        "S120000808": "Vanderbilt Law Review",
        "S67391710": "Virginia Law Review",
        "S161895660": "Yale Law Journal",
    },

    "linguistics": {
        "S183798913": "Applied Linguistics",
        "S88198767": "Cognition",
        "S192935290": "Discourse & Society",
        "S181779256": "Discourse Processes",
        "S4210197434": "First Language",
        "S2736822393": "Glossa",
        "S71689608": "International Journal of Bilingualism",
        "S61363356": "Journal of Linguistics",
        "S53787413": "Journal of Memory and Language",
        "S42504509": "Journal of Phonetics",
        "S186034587": "Journal of Pragmatics",
        "S81528758": "Journal of Sociolinguistics",
        "S159694083": "Laboratory Phonology",  # ISSN: 1868-6346
        "S176347361": "Language",
        "S207618182": "Language Acquisition",
        "S82334308": "Language Learning",
        "S121997567": "Language Variation and Change",
        "S123019783": "Language in Society",
        "S105737376": "Lingua",
        "S8506441": "Linguistic Inquiry",
        "S176883142": "Linguistics and Philosophy",
        "S72851247": "Modern Language Journal",
        "S36887808": "Natural Language & Linguistic Theory",
        "S23261261": "Phonology",
        "S201294665": "Second Language Research",
        "S84027950": "Studies in Second Language Acquisition",
        "S44683723": "Syntax",
        "S177238307": "TESOL Quarterly",
    },

    "literature": {
        "S43621796": "African American Review",
        "S183016999": "American Literature",
        "S122855400": "Comparative Literature",
        "S100243739": "Comparative Literature Studies",
        "S70019389": "Contemporary Literature",
        "S121755651": "Critical Inquiry",
        "S169145255": "ELH",
        "S192660949": "Feminist Studies",
        "S77594414": "Journal of Modern Literature",
        "S157531881": "Journal of Narrative Theory",
        "S4210169271": "MELUS",  # ISSN: 0163-755X
        "S93676754": "Modern Language Review",  # ISSN: 0026-7937
        "S185926442": "Modernism/modernity",
        "S174608640": "Narrative",
        "S117643613": "New Literary History",
        "S100105777": "Nineteenth-Century Literature",
        "S4210171065": "PMLA",  # ISSN: 0030-8129
        "S79803084": "Poetics Today",
        "S2735908585": "Renaissance Drama",
        "S94236332": "Representations",
        "S167911835": "Shakespeare Quarterly",
        "S2734450062": "Signs: Journal of Women in Culture and Society",
        "S161559975": "South Atlantic Quarterly",
        "S970496357": "Studies in English Literature 1500-1900",
        "S72126776": "Studies in the Novel",
        "S40751556": "Victorian Studies",
        "S12279879": "World Literature Today",
        "S171635450": "boundary 2",
    },

    "philosophy": {
        "S98143213": "American Philosophical Quarterly",
        "S121299002": "Analysis",  # ISSN: 0003-2638
        "S33792061": "Archiv für Geschichte der Philosophie",  # ISSN: 0003-9101
        "S98189702": "Australasian Journal of Philosophy",
        "S31551615": "Bioethics",
        "S176377974": "British Journal for the History of Philosophy",  # ISSN: 0960-8788
        "S107049385": "British Journal for the Philosophy of Science",
        "S41191225": "Canadian Journal of Philosophy",
        "S63151042": "Erkenntnis",
        "S184849641": "Ethics",
        "S14411630": "European Journal of Philosophy",
        "S954855591": "History of Philosophy Quarterly",  # ISSN: 0740-0675
        "S96509893": "Journal of Moral Philosophy",
        "S41650241": "Journal of Philosophy",
        "S81746323": "Journal of Political Philosophy",
        "S80702723": "Journal of the History of Philosophy",  # ISSN: 0022-5053
        "S159607754": "Kennedy Institute of Ethics Journal",
        "S37480348": "Mind",
        "S4306521046": "Nous",
        "S81959571": "Philosophical Quarterly",
        "S35579339": "Philosophical Review",
        "S147022693": "Philosophical Studies",
        "S117069359": "Philosophical Topics",  # ISSN: 0276-2080
        "S15279844": "Philosophy & Public Affairs",
        "S34011028": "Philosophy Compass",  # ISSN: 1747-9991
        "S204374153": "Philosophy and Phenomenological Research",
        "S147691735": "Philosophy of Science",
        "S108709262": "Ratio",  # ISSN: 0034-0006
        "S4210203962": "Social Philosophy and Policy",
        "S963759008": "Studia Leibnitiana",  # ISSN: 0039-3185
        "S255146": "Synthese",
        "S162880254": "Theoria",  # ISSN: 0040-5825
    },

    "religious-studies": {
        "S139284966": "Buddhist Studies Review",
        "S40661788": "Catholic Biblical Quarterly",  # ISSN: 0008-7912
        "S203378611": "Church History",
        "S117099692": "Harvard Theological Review",
        "S55827047": "Journal of Biblical Literature",
        "S31769938": "Journal of Ecclesiastical History",  # ISSN: 0022-0469
        "S67703274": "Journal of Religion",  # ISSN: 0022-4197
        "S21143573": "Journal of Religion in Africa",
        "S93503785": "Journal of Religious Ethics",
        "S149275985": "Journal of Theological Studies",  # ISSN: 0022-5185
        "S173718193": "Journal of the American Academy of Religion",
        "S178989728": "Method & Theory in the Study of Religion",
        "S185278035": "Modern Theology",
        "S111681200": "New Testament Studies",
        "S16595306": "Numen",
        "S207420867": "Religion",  # ISSN: 0021-8294
        "S124201077": "Religious Studies",
        "S75543290": "Studies in Religion/Sciences Religieuses",  # ISSN: 0008-4298
        "S43703656": "Theology Today",
    },


    # =========================================================================
    # NATURAL SCIENCES
    # =========================================================================

    "biology": {
        "S119405978": "Annual Review of Ecology, Evolution, and Systematics",
        "S110447773": "Cell",
        "S128425624": "Current Biology",
        "S80967739": "Ecology Letters",
        "S81160022": "Genome Biology",
        "S43092948": "Genome Research",
        "S57552105": "Molecular Biology and Evolution",
        "S156208185": "Molecular Cell",
        "S137773608": "Nature",
        "S64187185": "Nature Communications",
        "S2764884935": "Nature Ecology & Evolution",
        "S137905309": "Nature Genetics",
        "S134668137": "Nucleic Acids Research",
        "S154343897": "PLoS Biology",
        "S103870658": "PLoS Genetics",
        "S125754415": "Proceedings of the National Academy of Sciences",
        "S3006207977": "Proceedings of the Royal Society B: Biological Sciences",
        "S3880285": "Science",
        "S2737427234": "Science Advances",
        "S65478581": "Systematic Biology",
        "S118628157": "Trends in Cell Biology",
        "S79131028": "Trends in Ecology & Evolution",
        "S139283865": "Trends in Genetics",
        "S1336409049": "eLife",
    },

    "chemistry": {
        "S164001016": "ACS Applied Materials & Interfaces",
        "S37391459": "ACS Catalysis",
        "S2765035057": "ACS Central Science",
        "S145476921": "ACS Nano",
        "S145378405": "Accounts of Chemical Research",
        "S191963794": "Analytical Chemistry",
        "S67393510": "Angewandte Chemie International Edition",
        "S152760256": "Chemical Communications",
        "S41143188": "Chemical Reviews",
        "S184645833": "Chemical Science",
        "S66104727": "Chemistry of Materials",
        "S13479253": "Environmental Science & Technology",
        "S55009144": "Green Chemistry",
        "S171072222": "Inorganic Chemistry",
        "S77047749": "Journal of Chemical Physics",
        "S162030435": "Journal of Medicinal Chemistry",
        "S205050996": "Journal of Organic Chemistry",
        "S123480357": "Journal of Physical Chemistry Letters",
        "S111155417": "Journal of the American Chemical Society",
        "S177196338": "Macromolecules",
        "S143846845": "Nano Letters",
        "S202193212": "Nature Chemistry",
        "S201989124": "Organic Letters",
    },

    "earth-sciences": {
        "S119230507": "Earth and Planetary Science Letters",
        "S40187045": "Earth-Science Reviews",
        "S7538555": "Geochimica et Cosmochimica Acta",
        "S56162041": "Geology",
        "S36624081": "Geophysical Research Letters",
        "S32973720": "Global Biogeochemical Cycles",
        "S207178839": "Journal of Geophysical Research: Atmospheres",
        "S4210200322": "Journal of Geophysical Research: Oceans",
        "S4210228715": "Journal of Geophysical Research: Solid Earth",
        "S48977010": "Nature Geoscience",
        "S4210175021": "Paleoceanography and Paleoclimatology",
        "S6410836": "Tectonics",
    },

    "environmental-science": {
        "S5491134": "Annual Review of Environment and Resources",
        "S113876312": "Climate Policy",
        "S204799461": "Climatic Change",
        "S98137347": "Conservation Biology",
        "S136211407": "Ecological Economics",
        "S139338987": "Environmental Research Letters",
        "S39803240": "Environmental Science & Policy",
        "S13479253": "Environmental Science & Technology",
        "S74970393": "Global Change Biology",
        "S130750583": "Global Environmental Change",
        "S200872515": "Journal of Environmental Economics and Management",
        "S183584863": "Nature Climate Change",
        "S4210188283": "Nature Sustainability",
        "S4210191196": "One Earth",
    },

    "physics": {
        "S105243760": "Applied Physics Letters",
        "S205231332": "Astronomy & Astrophysics",
        "S1980519": "Astrophysical Journal",
        "S171172751": "Classical and Quantum Gravity",
        "S187991544": "Journal of Applied Physics",
        "S152000018": "Journal of Fluid Mechanics",
        "S187585107": "Journal of High Energy Physics",
        "S79244937": "Journal of Physics A: Mathematical and Theoretical",
        "S167943036": "Journal of Statistical Mechanics: Theory and Experiment",
        "S195663288": "Monthly Notices of the Royal Astronomical Society",
        "S156274416": "Nature Physics",
        "S148121101": "New Journal of Physics",
        "S4210194812": "Nuclear Physics B",
        "S4210197940": "Optica",
        "S178776955": "Optics Express",
        "S164566984": "Physical Review A",
        "S4210174675": "Physical Review B",
        "S4210190737": "Physical Review D",
        "S35412551": "Physical Review E",
        "S24807848": "Physical Review Letters",
        "S137042341": "Physical Review X",
        "S48633963": "Physics Reports",
        "S105282323": "Reports on Progress in Physics",
        "S73260565": "Reviews of Modern Physics",
    },


    # =========================================================================
    # SOCIAL SCIENCES
    # =========================================================================

    "business": {
        "S27614628": "Academy of Management Annals",  # ISSN: 1941-6067
        "S117778295": "Academy of Management Journal",
        "S33741590": "Academy of Management Perspectives",  # ISSN: 1558-9080
        "S46763546": "Academy of Management Review",
        "S143668711": "Administrative Science Quarterly",
        "S172782825": "California Management Review",  # ISSN: 0008-1256
        "S65924262": "Contemporary Accounting Research",
        "S187626162": "Entrepreneurship Theory and Practice",
        "S134094273": "Human Resource Management",  # ISSN: 0090-4848
        "S145507837": "Industrial and Corporate Change",  # ISSN: 0960-6491
        "S202812398": "Information Systems Research",
        "S111116695": "Journal of Accounting Research",
        "S62142384": "Journal of Accounting and Economics",
        "S76633192": "Journal of Business Ethics",
        "S93284759": "Journal of Business Research",  # ISSN: 0148-2963
        "S66201313": "Journal of Business Venturing",
        "S145429826": "Journal of Consumer Research",
        "S5353659": "Journal of Finance",
        "S149240962": "Journal of Financial Economics",
        "S38024979": "Journal of International Business Studies",
        "S122767448": "Journal of Management",
        "S151705444": "Journal of Management Studies",
        "S142990027": "Journal of Marketing",
        "S119950638": "Journal of Marketing Research",
        "S142306484": "Journal of Operations Management",
        "S93630570": "Journal of Product Innovation Management",
        "S159120381": "Journal of Retailing",
        "S125608309": "Journal of Service Research",
        "S78792899": "Journal of Small Business Management",
        "S97320426": "Journal of Supply Chain Management",
        "S143995394": "Journal of World Business",  # ISSN: 1090-9516
        "S92522684": "Journal of the Academy of Marketing Science",
        "S9435936": "Long Range Planning",  # ISSN: 0024-6301
        "S57293258": "MIS Quarterly",
        "S33323087": "Management Science",
        "S163534328": "Marketing Science",
        "S125775545": "Operations Research",
        "S206124708": "Organization Science",
        "S28882882": "Organization Studies",  # ISSN: 0170-8406
        "S149070780": "Production and Operations Management",
        "S9731383": "Research Policy",  # ISSN: 0048-7333
        "S11853582": "Review of Accounting Studies",
        "S170137484": "Review of Financial Studies",
        "S102949365": "Strategic Management Journal",
        "S160506855": "The Accounting Review",
    },

    "communications": {
        "S2764627845": "Annals of the International Communication Association",  # ISSN: 2380-8977
        "S193040567": "Communication Methods and Measures",  # ISSN: 1931-2458
        "S173776643": "Communication Monographs",  # ISSN: 0363-7751
        "S28604305": "Communication Research",
        "S103253184": "Communication Theory",
        "S2764497610": "Digital Journalism",
        "S49080740": "European Journal of Communication",
        "S195553305": "Human Communication Research",
        "S70010600": "Information, Communication & Society",
        "S143982487": "Journal of Broadcasting & Electronic Media",
        "S107737141": "Journal of Communication",
        "S30594836": "Journal of Computer-Mediated Communication",  # ISSN: 1083-6101
        "S27931387": "Journal of Health Communication",  # ISSN: 1081-0730
        "S111964278": "Journalism",  # ISSN: 1464-8849
        "S4210180660": "Journalism & Mass Communication Quarterly",
        "S119437531": "Journalism Studies",
        "S153570774": "Mass Communication and Society",
        "S97866008": "Media Psychology",  # ISSN: 1521-3269
        "S18522216": "Media, Culture & Society",
        "S4210178022": "New Media & Society",
        "S4306532188": "Political Communication",
        "S135539873": "Public Opinion Quarterly",
        "S2764570952": "Social Media + Society",  # ISSN: 2056-3051
        "S161861253": "The International Journal of Press/Politics",  # ISSN: 1040-1620
    },

    "economics": {
        "S42893225": "American Economic Journal: Applied Economics",
        "S158011328": "American Economic Journal: Economic Policy",
        "S170166683": "American Economic Journal: Macroeconomics",
        "S96919139": "American Economic Journal: Microeconomics",
        "S23254222": "American Economic Review",
        "S4210174288": "American Economic Review: Insights",
        "S4210173904": "Brookings Papers on Economic Activity",  # ISSN: 0007-2303
        "S95464858": "Econometrica",
        "S45992627": "Economic Journal",
        "S99606308": "Economic Policy",  # ISSN: 0266-4658
        "S69338747": "European Economic Review",
        "S181493553": "Experimental Economics",
        "S94044085": "Games and Economic Behavior",
        "S21260181": "IMF Economic Review",  # ISSN: 2041-4161
        "S179979277": "International Economic Review",  # ISSN: 0020-6598
        "S85739584": "Journal of Applied Econometrics",  # ISSN: 0883-7252
        "S2876017": "Journal of Banking & Finance",
        "S152282257": "Journal of Corporate Finance",
        "S101209419": "Journal of Development Economics",
        "S127742747": "Journal of Econometrics",
        "S62201805": "Journal of Economic Behavior & Organization",
        "S44585919": "Journal of Economic Dynamics and Control",  # ISSN: 0165-1889
        "S181171746": "Journal of Economic Growth",
        "S127708089": "Journal of Economic Literature",
        "S72880728": "Journal of Economic Perspectives",
        "S149131268": "Journal of Economic Theory",
        "S200872515": "Journal of Environmental Economics and Management",
        "S5353659": "Journal of Finance",
        "S149240962": "Journal of Financial Economics",
        "S5984737": "Journal of Financial Intermediation",
        "S166621295": "Journal of Health Economics",
        "S198098467": "Journal of International Economics",
        "S8557221": "Journal of Labor Economics",
        "S176795851": "Journal of Macroeconomics",
        "S6711363": "Journal of Monetary Economics",
        "S95323914": "Journal of Political Economy",
        "S199447588": "Journal of Public Economics",
        "S147692640": "Journal of Urban Economics",
        "S165087003": "Journal of the European Economic Association",
        "S136745531": "Macroeconomic Dynamics",
        "S92565720": "Oxford Bulletin of Economics and Statistics",  # ISSN: 0305-9049
        "S203860005": "Quarterly Journal of Economics",
        "S34139249": "RAND Journal of Economics",
        "S163499366": "Review of Economic Dynamics",  # ISSN: 1094-2025
        "S88935262": "Review of Economic Studies",
        "S180061323": "Review of Economics and Statistics",
        "S170137484": "Review of Financial Studies",
        "S78091837": "Review of World Economics",
        "S62957338": "The Journal of Human Resources",
        "S998097505": "The Journal of Law and Economics",
        "S2735890421": "World Bank Economic Review",  # ISSN: 0258-6770
    },

    "education": {
        "S185455288": "American Educational Research Journal",
        "S2940672": "Applied Measurement in Education",
        "S60281869": "British Educational Research Journal",  # ISSN: 0141-1926
        "S73080522": "Community College Review",
        "S168329810": "Comparative Education Review",  # ISSN: 0010-4086
        "S64506217": "Contemporary Educational Psychology",
        "S4888523": "Economics of Education Review",
        "S154498293": "Education Finance and Policy",
        "S124394548": "Educational Administration Quarterly",  # ISSN: 0013-161X
        "S138127711": "Educational Evaluation and Policy Analysis",
        "S187318745": "Educational Psychology Review",
        "S55175622": "Educational Researcher",
        "S129458801": "Harvard Educational Review",
        "S156367897": "International Journal of Educational Research",  # ISSN: 0883-0355
        "S10595604": "Journal of College Student Development",
        "S30638350": "Journal of Educational Measurement",
        "S61703936": "Journal of Educational Psychology",
        "S71326023": "Journal of Higher Education",
        "S177993953": "Journal of Literacy Research",  # ISSN: 1086-296X
        "S25370267": "Journal of Policy Analysis and Management",
        "S171036940": "Journal of Research in Science Teaching",  # ISSN: 0022-4308
        "S163858705": "Journal of Research on Educational Effectiveness",  # ISSN: 1934-5739
        "S89004459": "Journal of Teacher Education",
        "S78398831": "Learning and Instruction",
        "S2764537291": "Mathematics Education Research Journal",  # ISSN: 1033-2170
        "S55586218": "Oxford Review of Education",  # ISSN: 0305-4985
        "S102860129": "Reading Research Quarterly",  # ISSN: 0034-0553
        "S130619902": "Research in Higher Education",
        "S92895470": "Review of Educational Research",
        "S186832212": "Review of Higher Education",
        "S161883588": "Science Education",  # ISSN: 0036-8326
        "S36718530": "Sociology of Education",
        "S162196882": "Studies in Higher Education",
        "S74847328": "Teachers College Record",
        "S94618750": "Teaching and Teacher Education",
    },

    "political-science": {
        "S90314269": "American Journal of Political Science",
        "S176007004": "American Political Science Review",
        "S72844074": "American Politics Research",
        "S8194976": "Annual Review of Political Science",
        "S95691132": "British Journal of Political Science",
        "S105556297": "Comparative Political Studies",
        "S2764871768": "Comparative Politics",
        "S110268115": "Democratization",
        "S124584455": "Electoral Studies",
        "S40975480": "European Journal of International Relations",
        "S135158421": "European Journal of Political Research",
        "S62375027": "Governance",
        "S29411750": "Government and Opposition",
        "S160686149": "International Organization",
        "S99767407": "International Security",
        "S91639875": "International Studies Quarterly",
        "S20177303": "Journal of Conflict Resolution",
        "S151119180": "Journal of Democracy",
        "S22371039": "Journal of European Public Policy",
        "S71119591": "Journal of Peace Research",
        "S25370267": "Journal of Policy Analysis and Management",
        "S81746323": "Journal of Political Philosophy",
        "S95650557": "Journal of Politics",
        "S48869744": "Legislative Studies Quarterly",
        "S975761300": "PS: Political Science & Politics",
        "S6959732": "Party Politics",
        "S119514724": "Policy Studies Journal",
        "S29331042": "Political Analysis",
        "S110036823": "Political Behavior",
        "S108349823": "Political Research Quarterly",
        "S161027966": "Political Science Quarterly",
        "S2764571748": "Political Science Research and Methods",
        "S25369639": "Political Theory",
        "S103858575": "Presidential Studies Quarterly",
        "S76877748": "Public Administration Review",
        "S135539873": "Public Opinion Quarterly",
        "S44648735": "Quarterly Journal of Political Science",
        "S108218269": "Regulation & Governance",
        "S2738497388": "Research & Politics",
        "S131264395": "Review of International Studies",
        "S200906791": "Security Studies",
        "S148921865": "State Politics & Policy Quarterly",
        "S179028992": "West European Politics",
        "S143110675": "World Politics",
    },

    "psychology": {
        "S90670110": "Annual Review of Psychology",
        "S137478622": "Behavior Research Methods",
        "S109723506": "Child Development",
        "S2764897075": "Clinical Psychological Science",
        "S88198767": "Cognition",
        "S36783443": "Cognitive Psychology",  # ISSN: 0010-0285
        "S78735424": "Cognitive Science",
        "S116196263": "Cortex",  # ISSN: 0010-9452
        "S126635229": "Developmental Psychology",
        "S154906575": "Developmental Science",  # ISSN: 1363-755X
        "S118198609": "Emotion",
        "S10288104": "European Journal of Social Psychology",
        "S34137071": "Health Psychology",
        "S67039580": "Infant Behavior and Development",  # ISSN: 0163-6383
        "S121947241": "Journal of Abnormal Psychology",
        "S166002381": "Journal of Applied Psychology",
        "S123144817": "Journal of Cognitive Neuroscience",
        "S118719888": "Journal of Consulting and Clinical Psychology",
        "S201005279": "Journal of Experimental Child Psychology",  # ISSN: 0022-0965
        "S62013203": "Journal of Experimental Psychology: General",
        "S18666220": "Journal of Experimental Psychology: Learning, Memory, and Cognition",
        "S12410666": "Journal of Experimental Social Psychology",
        "S50147421": "Journal of Family Psychology",
        "S53787413": "Journal of Memory and Language",
        "S160573970": "Journal of Organizational Behavior",
        "S29984966": "Journal of Personality and Social Psychology",
        "S156995526": "Journal of Research in Personality",
        "S25746158": "Journal of Vocational Behavior",
        "S114265899": "Memory & Cognition",  # ISSN: 0090-502X
        "S64250036": "Multivariate Behavioral Research",
        "S2764866340": "Nature Human Behaviour",
        "S165368631": "Neuropsychologia",  # ISSN: 0028-3932
        "S97426521": "Neuropsychology",
        "S64744539": "Organizational Behavior and Human Decision Processes",
        "S187348256": "Personality and Social Psychology Bulletin",
        "S84664706": "Personnel Psychology",
        "S27228949": "Perspectives on Psychological Science",
        "S75627607": "Psychological Bulletin",
        "S71144982": "Psychological Medicine",
        "S45419345": "Psychological Methods",
        "S35223124": "Psychological Review",
        "S58854535": "Psychological Science",
        "S55618883": "Psychology and Aging",  # ISSN: 0882-7974
        "S138679565": "Psychonomic Bulletin & Review",  # ISSN: 1069-9384
        "S167723465": "Psychophysiology",
        "S177779441": "Social Cognition",
        "S192051125": "Trends in Cognitive Sciences",
    },

    "public-policy": {
        "S5465880": "Administration & Society",
        "S106702950": "American Review of Public Administration",  # ISSN: 0275-0740
        "S62375027": "Governance",
        "S63571029": "International Public Management Journal",
        "S16140064": "International Review of Administrative Sciences",
        "S77082647": "Journal of Comparative Policy Analysis",  # ISSN: 1387-6988
        "S22371039": "Journal of European Public Policy",
        "S25370267": "Journal of Policy Analysis and Management",
        "S169433491": "Journal of Public Administration Research and Theory",
        "S76906069": "Journal of Public Policy",
        "S17167983": "Policy & Politics",
        "S197895017": "Policy Sciences",
        "S119514724": "Policy Studies Journal",
        "S201221823": "Public Administration",
        "S76877748": "Public Administration Review",
        "S37623806": "Public Management Review",
        "S17185278": "Public Policy and Administration",
        "S108218269": "Regulation & Governance",
        "S54913114": "Review of Policy Research",
    },

    "sociology": {
        "S143668711": "Administrative Science Quarterly",
        "S20589029": "American Behavioral Scientist",
        "S122471516": "American Journal of Sociology",
        "S157620343": "American Sociological Review",
        "S61274580": "Annual Review of Sociology",
        "S173252385": "British Journal of Sociology",
        "S161221444": "City and Community",
        "S67613863": "Criminology",
        "S30543418": "Demography",
        "S96629499": "Ethnic and Racial Studies",
        "S159327246": "European Sociological Review",
        "S113116626": "Gender & Society",
        "S90857023": "International Migration Review",  # ISSN: 0197-9183
        "S17740374": "Journal of Contemporary Ethnography",
        "S149872823": "Journal of Ethnic and Migration Studies",  # ISSN: 1369-183X
        "S122290859": "Journal of Health and Social Behavior",
        "S146344": "Journal of Marriage and Family",
        "S173027916": "Journal of Research in Crime and Delinquency",
        "S44706263": "Law & Society Review",
        "S190942573": "Mobilization",
        "S98355519": "Poetics",  # ISSN: 0304-422X
        "S202512192": "Population Studies",  # ISSN: 0032-4728
        "S32314625": "Population and Development Review",
        "S143967217": "Qualitative Sociology",
        "S159612214": "Research in Social Stratification and Mobility",
        "S130611943": "Social Forces",
        "S135892541": "Social Movement Studies",
        "S26186134": "Social Networks",  # ISSN: 0378-8733
        "S129389861": "Social Problems",
        "S131591925": "Social Psychology Quarterly",
        "S59311786": "Social Science Research",
        "S193359815": "Sociological Forum",  # ISSN: 0884-8971
        "S9536269": "Sociological Methods & Research",
        "S195570583": "Sociological Perspectives",  # ISSN: 0731-1214
        "S66666449": "Sociological Quarterly",  # ISSN: 0038-0253
        "S60621485": "Sociological Theory",
        "S36718530": "Sociology of Education",
        "S136778369": "Sociology of Religion",  # ISSN: 1069-4404
        "S4210195209": "Socius",
        "S118419795": "Theory and Society",
        "S50366009": "Urban Studies",
        "S51211322": "Work and Occupations",
    },

}


# ISSN mapping for Crossref fallback
JOURNAL_ISSNS = {
    "Art Bulletin": "0004-3079",
    "Burlington Magazine": "0007-6287",
    "Zeitschrift für Kunstgeschichte": "0044-2992",
    "Artforum": "1086-7058",
    "Academy of Management Perspectives": "1558-9080",
    "Academy of Management Annals": "1941-6067",
    "Organization Studies": "0170-8406",
    "Human Resource Management": "0090-4848",
    "Journal of World Business": "1090-9516",
    "Long Range Planning": "0024-6301",
    "Research Policy": "0048-7333",
    "Journal of Business Research": "0148-2963",
    "Industrial and Corporate Change": "0960-6491",
    "California Management Review": "0008-1256",
    "The International Journal of Press/Politics": "1040-1620",
    "Communication Monographs": "0363-7751",
    "Annals of the International Communication Association": "2380-8977",
    "Journal of Computer-Mediated Communication": "1083-6101",
    "Social Media + Society": "2056-3051",
    "Journalism": "1464-8849",
    "Media Psychology": "1521-3269",
    "Communication Methods and Measures": "1931-2458",
    "Journal of Health Communication": "1081-0730",
    "IEEE Transactions on Computers": "0018-9340",
    "ACM Transactions on Programming Languages and Systems": "0164-0925",
    "IEEE Transactions on Dependable and Secure Computing": "1545-5971",
    "IEEE Transactions on Mobile Computing": "1536-1233",
    "ACM Transactions on Information Systems": "1046-8188",
    "Information Systems": "0306-4379",
    "Data Mining and Knowledge Discovery": "1384-5810",
    "IEEE Transactions on Image Processing": "1057-7149",
    "Computer Vision and Image Understanding": "1077-3142",
    "International Journal of Computer Vision": "0920-5691",
    "Pattern Recognition": "0031-3203",
    "Neural Networks": "0893-6080",
    "Neurocomputing": "0925-2312",
    "Expert Systems with Applications": "0957-4174",
    "Knowledge-Based Systems": "0950-7051",
    "Artificial Intelligence Review": "0269-2821",
    "Computational Linguistics": "0891-2017",
    "Transactions of the Association for Computational Linguistics": "2307-387X",
    "Journal of Applied Econometrics": "0883-7252",
    "Oxford Bulletin of Economics and Statistics": "0305-9049",
    "Brookings Papers on Economic Activity": "0007-2303",
    "IMF Economic Review": "2041-4161",
    "World Bank Economic Review": "0258-6770",
    "Economic Policy": "0266-4658",
    "Review of Economic Dynamics": "1094-2025",
    "Journal of Economic Dynamics and Control": "0165-1889",
    "International Economic Review": "0020-6598",
    "British Educational Research Journal": "0141-1926",
    "Oxford Review of Education": "0305-4985",
    "Comparative Education Review": "0010-4086",
    "International Journal of Educational Research": "0883-0355",
    "Educational Administration Quarterly": "0013-161X",
    "Journal of Research on Educational Effectiveness": "1934-5739",
    "Science Education": "0036-8326",
    "Journal of Research in Science Teaching": "0022-4308",
    "Reading Research Quarterly": "0034-0553",
    "Journal of Literacy Research": "1086-296X",
    "Mathematics Education Research Journal": "1033-2170",
    "IEEE Transactions on Circuits and Systems I": "1549-8328",
    "IEEE Transactions on Circuits and Systems II": "1057-7130",
    "Electronics Letters": "0013-5194",
    "William and Mary Quarterly": "0043-5597",
    "Journal of Southern History": "0022-4642",
    "Journal of the Early Republic": "0275-1275",
    "Civil War History": "0009-8078",
    "Diplomatic History": "0145-2096",
    "Journal of Contemporary History": "0022-0094",
    "Journal of Medieval History": "0304-4181",
    "Journal of the History of Medicine and Allied Sciences": "0022-5045",
    "Bulletin of the History of Medicine": "0007-5140",
    "Isis": "0021-1753",
    "Technology and Culture": "0040-165X",
    "History of Science": "0073-2753",
    "Journal of Global History": "1740-0228",
    "International History Review": "0707-5332",
    "Holocaust and Genocide Studies": "1476-7937",
    "Cornell Law Review": "0010-8847",
    "Georgetown Law Journal": "0016-8092",
    "University of Chicago Law Review": "0041-9494",
    "Boston University Law Review": "0006-8047",
    "Minnesota Law Review": "0026-5535",
    "American Journal of Comparative Law": "0002-919X",
    "Modern Law Review": "0026-7961",
    "Oxford Journal of Legal Studies": "0143-6503",
    "Legal Theory": "1352-3252",
    "Law and Philosophy": "0167-5249",
    "Journal of Law and Economics": "2963-7937",
    "Journal of Legal Analysis": "1946-5319",
    "American Criminal Law Review": "0164-0364",
    "Journal of Criminal Law and Criminology": "0091-4169",
    "Laboratory Phonology": "1868-6346",
    "PMLA": "0030-8129",
    "Modern Language Review": "0026-7937",
    "MELUS": "0163-755X",
    "Analysis": "0162-8828",
    "Philosophical Topics": "0276-2080",
    "Philosophy Compass": "1747-9991",
    "Ratio": "0034-0006",
    "Theoria": "0040-5825",
    "Journal of the History of Philosophy": "0022-5053",
    "History of Philosophy Quarterly": "0740-0675",
    "British Journal for the History of Philosophy": "0960-8788",
    "Archiv für Geschichte der Philosophie": "0003-9101",
    "Studia Leibnitiana": "0039-3185",
    "Cognitive Psychology": "0010-0285",
    "Memory & Cognition": "0090-502X",
    "Psychonomic Bulletin & Review": "1069-9384",
    "Journal of Experimental Child Psychology": "0022-0965",
    "Developmental Science": "1363-755X",
    "Infant Behavior and Development": "0163-6383",
    "Psychology and Aging": "0882-7974",
    "Neuropsychologia": "0028-3932",
    "Cortex": "0010-9452",
    "American Review of Public Administration": "0275-0740",
    "Journal of Comparative Policy Analysis": "1387-6988",
    "Journal of Religion": "0022-4197",
    "Religion": "0021-8294",
    "Catholic Biblical Quarterly": "0008-7912",
    "Journal of Ecclesiastical History": "0022-0469",
    "Journal of Theological Studies": "0022-5185",
    "Studies in Religion/Sciences Religieuses": "0008-4298",
    "Population Studies": "0032-4728",
    "Sociological Forum": "0884-8971",
    "Sociological Quarterly": "0038-0253",
    "Sociological Perspectives": "0731-1214",
    "Social Networks": "0378-8733",
    "Poetics": "0304-422X",
    "Journal of Ethnic and Migration Studies": "1369-183X",
    "International Migration Review": "0197-9183",
    "Sociology of Religion": "1069-4404",
}


def get_journals_for_discipline(discipline_slug: str) -> dict:
    """Get journal mapping for a discipline."""
    return JOURNALS_BY_DISCIPLINE.get(discipline_slug, {})


def get_all_discipline_slugs() -> list:
    """Get list of all disciplines with journal mappings."""
    return list(JOURNALS_BY_DISCIPLINE.keys())


def get_issn_for_journal(journal_name: str) -> str | None:
    """Get ISSN for a journal name (for Crossref fallback)."""
    return JOURNAL_ISSNS.get(journal_name)
