"""
Canonical 119-subfield keywords for LiterView taxonomy classifier.

DO NOT EDIT MANUALLY — generated by classifier/build_canonical_subfield_keywords.py.

Source: classifier/subfields.yaml (9 disciplines / 119 competitive slots + 1 overlay + 'other').
  - 56 subfields use legacy_keywords from the YAML (curated 2026-04-14).
  - 63 subfields use NEW_KEYWORDS dict in the generator (curated 2026-05-25).

Structure: discipline_slug -> subfield_slug -> {display_name, keywords}.
Keywords are matched against title + abstract + journal name (case-insensitive,
word-boundary regex with optional plural suffix) by pipeline/classify_subfields.py.

OVERLAY subfields (`overlay: true` in subfields.yaml) are DELIBERATELY ABSENT from
SUBFIELD_KEYWORDS: they ride on top of a base slot label and must never win a
competitive fallback assignment or be a paper's only subfield. Omitting them here
makes that structurally impossible for every keyword classifier that reads this
file — including the mirrored academic-crawler copy. Their names are listed in
OVERLAY_SUBFIELDS so the full canonical set is still reconstructible.
"""

OVERLAY_SUBFIELDS = {'american-political-economy'}

SUBFIELD_KEYWORDS = {
    'business': {
        'accounting': {
            'display_name': 'Accounting',
            'keywords': [
                'accounting', 'audit', 'financial reporting', 'gaap', 'ifrs', 'earnings management',
                'accrual', 'disclosure', 'auditor', 'tax', 'bookkeeping', 'balance sheet',
                'revenue recognition',
            ],
        },
        'business-finance': {
            'display_name': 'Business Finance',
            'keywords': [
                'corporate finance', 'capital structure', 'payout policy', 'M&A finance',
                'asset pricing business', 'behavioral finance empirical', 'financial intermediary',
                'market microstructure', 'household finance', 'consumer finance',
                'entrepreneurial finance', 'real estate finance', 'FinTech',
                'initial public offering', 'IPO', 'governance finance', 'dividend policy',
                'leverage firm', 'debt finance firm',
            ],
        },
        'entrepreneurship': {
            'display_name': 'Entrepreneurship',
            'keywords': [
                'entrepreneur', 'startup', 'venture', 'innovation', 'new venture', 'founder',
                'small business',
            ],
        },
        'human-resource-management': {
            'display_name': 'Human Resource Management',
            'keywords': [
                'staffing', 'employee selection', 'recruitment', 'compensation and benefits',
                'performance management', 'employee training', 'strategic HRM', 'SHRM',
                'industrial relations', 'employee benefit', 'HR analytics',
                'labor-management relations', 'HR policy', 'employee development', 'HRM practice',
                'employee retention', 'talent management', 'workforce management',
            ],
        },
        'information-systems': {
            'display_name': 'Information Systems / MIS',
            'keywords': [
                'IT adoption', 'IT use', 'digital platform IS', 'IS design science',
                'socio-technical IT', 'IS strategy', 'cybersecurity management',
                'AI in organization', 'ML in organization', 'data governance', 'crowdsourcing',
                'online community', 'online marketplace', 'MIS', 'management information system',
                'technology acceptance', 'TAM', 'UTAUT',
            ],
        },
        'innovation-technology-mgmt': {
            'display_name': 'Technology and Innovation Management',
            'keywords': [
                'R&D management', 'patent innovation firm', 'open innovation',
                'technology platform strategy', 'digital transformation',
                'technology diffusion firm', 'absorptive capacity', 'knowledge management firm',
                'innovation network firm', 'technology alliance', 'technology strategy',
                'innovation strategy', 'technology adoption firm', 'technology transfer',
                'innovation performance', 'technology commercialization', 'breakthrough innovation',
                'organizational ambidexterity',
            ],
        },
        'international-business': {
            'display_name': 'International Business and Global Strategy',
            'keywords': [
                'MNE', 'multinational enterprise', 'FDI', 'foreign direct investment',
                'internationalization', 'cross-border M&A', 'emerging market firm',
                'institutional void', 'cross-cultural management', 'global value chain',
                'international HRM', 'host country firm', 'MNE subsidiary',
                'international strategy', 'non-market strategy international', 'MNE strategy',
                'global strategy firm', 'internationalisation',
            ],
        },
        'marketing-consumer': {
            'display_name': 'Consumer Behavior / Marketing-Consumer',
            'keywords': [
                'marketing', 'consumer', 'brand', 'advertising', 'pricing', 'customer', 'purchase',
                'retail',
            ],
        },
        'marketing-quant': {
            'display_name': 'Quantitative Marketing / Marketing Science',
            'keywords': [
                'choice modeling', 'BLP marketing', 'structural demand marketing',
                'structural IO marketing', 'CRM', 'customer analytics', 'advertising attribution',
                'advertising lift', 'pricing model', 'promotion model', 'recommender system',
                'algorithmic marketing', 'digital marketing empirics',
                'platform marketing empirics', 'conjoint', 'marketing demand estimation',
                'hierarchical Bayes', 'marketing mix model', 'customer lifetime value', 'CLV',
            ],
        },
        'operations-management': {
            'display_name': 'Operations Management and Supply Chain',
            'keywords': [
                'supply chain', 'operations', 'inventory', 'logistics', 'manufacturing', 'quality',
                'production', 'process',
            ],
        },
        'operations-research': {
            'display_name': 'Operations Research / Management Science (Methods)',
            'keywords': [
                'mathematical programming', 'stochastic optimization', 'queueing model',
                'simulation methodology', 'decision analysis', 'revenue management model',
                'network optimization', 'analytics methodology', 'algorithmic OR',
                'integer programming', 'linear programming', 'dynamic programming',
                'Markov decision', 'vehicle routing', 'supply chain optimization', 'network flow',
                'combinatorial optimization', 'operations research',
            ],
        },
        'organization-theory': {
            'display_name': 'Organization Theory / Macro-OB',
            'keywords': [
                'institutional theory', 'organizational ecology', 'organizational field',
                'organizational category', 'market category', 'organizational identity',
                'organizational routine', 'organizational learning', 'organizational design',
                'organizational change', 'institutional isomorphism', 'organizational legitimacy',
                'organizational form', 'population ecology', 'neo-institutional',
                'organizational evolution', 'sociology of organization', 'niche organization',
            ],
        },
        'organizational-behavior': {
            'display_name': 'Organizational Behavior (Micro)',
            'keywords': [
                'motivation work', 'job attitude', 'job satisfaction', 'work engagement',
                'team leadership organizational', 'workplace emotion', 'organizational justice',
                'employee voice', 'power at work', 'workplace diversity micro',
                'employee well-being', 'organizational citizenship behavior', 'OCB',
                'transformational leadership', 'ethical leadership', 'abusive supervision',
                'team performance', 'employee creativity',
            ],
        },
        'strategy': {
            'display_name': 'Strategic Management',
            'keywords': [
                'management', 'strategy', 'competitive advantage', 'firm performance',
                'organizational', 'ceo', 'executive', 'governance',
            ],
        },
    },
    'communications': {
        'critical-cultural-media-studies': {
            'display_name': 'Critical and Cultural Media Studies',
            'keywords': [
                'cultural studies media', 'critical theory media', 'feminist media',
                'critical race media', 'queer media', 'LGBTQ media studies', 'postcolonial media',
                'decolonial media', 'fan studies', 'popular culture studies', 'performance studies',
                'critical discourse analysis', 'political economy of media', 'Herman Chomsky',
                'hegemony media', 'media representation', 'encoding decoding', 'audience reception',
            ],
        },
        'digital-media-cmc-platforms': {
            'display_name': 'Digital Media, CMC, and Platforms',
            'keywords': [
                'social media', 'twitter', 'facebook', 'online', 'internet', 'viral', 'platform',
                'algorithm', 'digital',
            ],
        },
        'health-communication': {
            'display_name': 'Health Communication',
            'keywords': [
                'patient-provider communication', 'health campaign', 'risk communication',
                'health crisis communication', 'health literacy', 'eHealth', 'mHealth',
                'vaccine communication', 'vaccine hesitancy', 'health misinformation',
                'health narrative', 'health-message tailoring', 'public health messaging',
                'prevention messaging', 'doctor-patient communication', 'medical communication',
                'telehealth communication', 'health promotion communication',
            ],
        },
        'intercultural-global-communication': {
            'display_name': 'Intercultural and Global Communication',
            'keywords': [
                'public opinion', 'polling', 'survey', 'attitude', 'perception', 'trust',
                'polarization',
            ],
        },
        'interpersonal-communication': {
            'display_name': 'Interpersonal Communication',
            'keywords': [
                'relational communication', 'family communication', 'nonverbal communication',
                'dyadic interaction', 'deception detection', 'social support communication',
                'interpersonal conflict', 'dark side communication',
                'romantic relationship communication', 'close relationship', 'self-disclosure',
                'communication apprehension', 'relational dialectics',
                'communication accommodation', 'interpersonal influence', 'relational maintenance',
                'supportive communication',
            ],
        },
        'journalism-studies': {
            'display_name': 'Journalism Studies',
            'keywords': [
                'newsroom', 'news production', 'journalistic role', 'journalistic ethics',
                'press freedom', 'news business model', 'audience and news', 'data journalism',
                'computational journalism', 'foreign correspondent', 'comparative journalism',
                'journalism history', 'news work', 'news industry', 'journalism education',
                'newsroom ethnography', 'freelance journalism', 'alternative media', 'news routine',
                'platform dependency',
            ],
        },
        'mass-communication-media-effects': {
            'display_name': 'Mass Communication and Media Effects',
            'keywords': [
                'media', 'news', 'journalism', 'press', 'broadcast', 'television', 'newspaper',
                'media effects', 'agenda setting',
            ],
        },
        'organizational-communication': {
            'display_name': 'Organizational Communication',
            'keywords': [
                'leadership communication', 'organizational socialization',
                'organizational culture', 'organizational identification', 'team communication',
                'organizational change communication', 'internal communication',
                'knowledge management communication', 'workplace diversity communication',
                'constitutive communication', 'CCO', 'employee voice communication',
                'organizational discourse', 'sensemaking organizational', 'organizational rhetoric',
                'organizational climate communication', 'superior-subordinate',
            ],
        },
        'political-communication': {
            'display_name': 'Political Communication',
            'keywords': [
                'political advertising', 'campaign', 'political news', 'propaganda',
                'misinformation', 'fact-checking', 'political rhetoric',
            ],
        },
        'rhetoric-public-address-argumentation': {
            'display_name': 'Rhetoric, Public Address, and Argumentation',
            'keywords': [
                'rhetorical criticism', 'rhetoric theory', 'public address',
                'presidential rhetoric', 'social movement rhetoric', 'argumentation theory',
                'debate forensics', 'deliberative rhetoric', 'public memory', 'commemoration',
                'rhetoric of science', 'visual rhetoric', 'multimodal rhetoric',
                'classical rhetoric', 'rhetorical analysis', 'rhetorical figure',
                'argumentation scheme', 'rhetorical situation',
            ],
        },
        'strategic-communication-pr-advertising': {
            'display_name': 'Strategic Communication, PR, and Advertising',
            'keywords': [
                'public relations', 'PR campaign', 'advertising effects', 'brand communication',
                'corporate communication', 'branding', 'reputation management', 'issue management',
                'stakeholder communication', 'integrated marketing communication', 'IMC',
                'sponsorship', 'branded content', 'native advertising', 'influencer marketing',
                'advertising effectiveness', 'message strategy', 'advocacy advertising',
            ],
        },
    },
    'economics': {
        'behavioral-economics': {
            'display_name': 'Behavioral Economics',
            'keywords': [
                'behavioral', 'nudge', 'heuristic', 'bias', 'prospect theory', 'loss aversion',
                'time preference', 'present bias', 'mental accounting', 'framing', 'default',
                'choice architecture',
            ],
        },
        'development-economics': {
            'display_name': 'Development Economics',
            'keywords': [
                'developing country', 'poverty', 'microfinance', 'rct', 'randomized',
                'field experiment', 'aid', 'economic development', 'growth', 'institution',
                'corruption', 'rule of law',
            ],
        },
        'econometrics': {
            'display_name': 'Econometrics',
            'keywords': [
                'causal inference', 'regression discontinuity', 'difference-in-differences',
                'instrumental variable', 'panel data', 'time series', 'gmm', 'maximum likelihood',
                'bootstrap', 'heteroskedasticity', 'regression', 'estimation', 'identification',
                'endogeneity', 'fixed effects', 'treatment effect', 'propensity score',
                'standard error', 'robust',
            ],
        },
        'economic-history': {
            'display_name': 'Economic History',
            'keywords': [
                'economic history', 'cliometrics', 'industrial revolution', 'historical GDP',
                'long-run growth', 'persistence study', 'institutional origins',
                'slavery economics', 'historical inequality', 'pre-industrial', 'great divergence',
                'historical demography', 'historical labor markets', 'financial history',
                'monetary history', 'gold standard', 'agrarian economy', 'demographic transition',
                'household economy',
            ],
        },
        'education-economics': {
            'display_name': 'Economics of Education',
            'keywords': [
                'returns to education', 'human capital', 'Mincer equation',
                'education production function', 'class size', 'teacher quality', 'school choice',
                'charter school', 'voucher', 'Head Start', 'Perry Preschool',
                'intergenerational mobility', 'college financial aid', 'Pell Grant',
                'college access', 'returns to college', 'early childhood intervention', 'PISA',
                'school inputs',
            ],
        },
        'energy-economics': {
            'display_name': 'Energy Economics',
            'keywords': [
                'energy', 'oil', 'gas', 'electricity', 'renewable', 'solar', 'wind', 'fossil fuel',
                'carbon', 'emission', 'power', 'fuel', 'petroleum',
            ],
        },
        'environmental-economics': {
            'display_name': 'Environmental Economics',
            'keywords': [
                'pollution regulation', 'abatement cost', 'environmental externality',
                'Pigouvian tax', 'contingent valuation', 'hedonic pricing', 'ecosystem services',
                'biodiversity economics', 'climate damage', 'integrated assessment', 'IAM',
                'carbon price', 'emissions permit', 'natural resource economics', 'fishery',
                'deforestation', 'willingness to pay', 'green growth', 'environmental justice',
                'non-market valuation',
            ],
        },
        'finance': {
            'display_name': 'Finance',
            'keywords': [
                'asset pricing', 'stock', 'bond', 'portfolio', 'risk premium', 'capm',
                'market efficiency', 'corporate finance', 'capital structure', 'dividend', 'ipo',
                'merger', 'venture capital', 'private equity', 'bank', 'banking', 'credit', 'loan',
                'lending', 'borrowing', 'deposit', 'financial', 'investment', 'investor', 'return',
                'shareholder', 'equity', 'valuation', 'profitability', 'liquidity', 'leverage',
            ],
        },
        'health-economics': {
            'display_name': 'Health Economics',
            'keywords': [
                'healthcare', 'health insurance', 'hospital', 'physician', 'medical cost',
                'pharmaceutical', 'drug pricing', 'medicare', 'medicaid', 'health spending',
            ],
        },
        'industrial-organization': {
            'display_name': 'Industrial Organization',
            'keywords': [
                'industrial organization', 'market structure', 'market power',
                'market concentration', 'antitrust', 'merger', 'vertical integration',
                'two-sided market', 'platform competition', 'structural demand', 'BLP', 'oligopoly',
                'monopoly power', 'network industry', 'competition policy', 'price discrimination',
                'advertising competition', 'product differentiation', 'entry deterrence',
                'merger review',
            ],
        },
        'international-economics': {
            'display_name': 'International Economics',
            'keywords': [
                'trade', 'export', 'import', 'tariff', 'globalization', 'outsourcing',
                'foreign direct investment', 'multinational', 'trade policy',
                'comparative advantage', 'trade agreement', 'wto', 'nafta',
            ],
        },
        'labor-economics': {
            'display_name': 'Labor Economics',
            'keywords': [
                'wage', 'employment', 'labor market', 'minimum wage', 'union', 'human capital',
                'education return', 'job search', 'unemployment insurance', 'labor supply',
                'occupational choice', 'discrimination', 'worker', 'job', 'occupation', 'earnings',
                'income', 'hiring', 'firing', 'workforce', 'skill', 'training', 'career', 'salary',
            ],
        },
        'law-and-economics': {
            'display_name': 'Law and Economics',
            'keywords': [
                'law and economics', 'economic analysis of law', 'optimal deterrence',
                'crime and punishment', 'economic analysis of contract', 'expectation damages',
                'optimal tort', 'negligence rule', 'public choice', 'legislative bargaining',
                'judicial behavior', 'regulation economics', 'antitrust economics',
                'behavioral law and economics', 'settlement bargaining', 'plea bargaining',
                'litigation economics', 'rational litigant',
            ],
        },
        'macroeconomics': {
            'display_name': 'Macroeconomics',
            'keywords': [
                'gdp', 'inflation', 'unemployment', 'business cycle', 'monetary policy',
                'fiscal policy', 'aggregate demand', 'aggregate supply', 'recession',
                'economic growth', 'central bank', 'interest rate', 'dsge', 'economy', 'growth',
                'output', 'investment', 'consumption', 'savings', 'exchange rate', 'currency',
                'debt', 'deficit', 'stimulus',
            ],
        },
        'microeconomics': {
            'display_name': 'Microeconomics',
            'keywords': [
                'consumer choice', 'utility', 'demand', 'supply', 'price elasticity',
                'market structure', 'monopoly', 'oligopoly', 'perfect competition', 'game theory',
                'mechanism design', 'auction', 'contract theory', 'incentive', 'moral hazard',
                'adverse selection', 'principal-agent', 'firm', 'producer', 'cost', 'profit',
                'price', 'market', 'equilibrium', 'competition', 'pricing', 'consumer', 'buyer',
                'seller', 'trade-off',
            ],
        },
        'public-economics': {
            'display_name': 'Public Economics',
            'keywords': [
                'taxation', 'tax', 'public good', 'public finance', 'welfare', 'social insurance',
                'government spending', 'redistribution', 'optimal taxation', 'tax evasion',
                'fiscal federalism', 'subsidy', 'transfer', 'benefit', 'pension', 'social security',
            ],
        },
    },
    'education': {
        'comparative-and-international-education': {
            'display_name': 'Comparative and International Education',
            'keywords': [
                'comparative education', 'international education', 'cross-national education',
                'education in LIC', 'education and international development', 'SDGs education',
                'global education policy', 'PISA effect', 'World Bank education',
                'UNESCO education', 'post-colonial education', 'decolonial education',
                'refugee education', 'emergency education', 'large-scale international assessment',
                'non-formal education', 'lifelong learning international',
            ],
        },
        'curriculum-and-subject-matter-education': {
            'display_name': 'Curriculum and Subject-Matter Education',
            'keywords': [
                'school', 'elementary', 'secondary', 'high school', 'middle school', 'teacher',
                'principal', 'classroom', 'curriculum', 'pupil', 'grade', 'instruction', 'lesson',
                'educational',
            ],
        },
        'early-childhood-education': {
            'display_name': 'Early Childhood Education',
            'keywords': [
                'preschool', 'pre-K education', 'Head Start', 'early literacy', 'early numeracy',
                'child care quality', 'kindergarten readiness', 'kindergarten transition',
                'early childhood policy', 'family engagement early childhood',
                'social-emotional development ECE', 'Montessori', 'Reggio Emilia', 'HighScope',
                'Tools of the Mind', 'ECE program', 'ECE workforce', 'pre-K program',
            ],
        },
        'education-policy-and-economics-of-education': {
            'display_name': 'Education Policy and Economics of Education',
            'keywords': [
                'K-12 policy', 'higher education policy', 'school finance reform',
                'school choice policy', 'charter school policy', 'accountability standards',
                'teacher labor market policy', 'teacher compensation policy',
                'returns to schooling policy', 'education and workforce policy',
                'politics of education', 'education reform policy', 'K-12 reform',
                'education governance', 'education finance reform', 'ESEA', 'Title I',
                'education-policy analysis',
            ],
        },
        'educational-leadership-and-administration': {
            'display_name': 'Educational Leadership and Administration',
            'keywords': [
                'principal leadership', 'instructional leadership', 'district leadership',
                'superintendent', 'school organizational change', 'distributed leadership',
                'transformational leadership school', 'school board', 'school governance',
                'leadership preparation', 'principal preparation', 'school improvement',
                'school turnaround', 'leadership development education',
                'educational administration', 'school administrator', 'district administration',
            ],
        },
        'educational-measurement-and-methodology': {
            'display_name': 'Educational Measurement and Methodology',
            'keywords': [
                'IRT', 'item response theory', 'multidimensional IRT', 'NAEP', 'PISA', 'TIMSS',
                'validity assessment', 'reliability assessment', 'fairness assessment',
                'standard setting', 'test development', 'computerized adaptive testing', 'CAT',
                'automated scoring', 'education program evaluation', 'causal inference education',
                'quasi-experiment education', 'multilevel education', 'longitudinal education',
                'psychometric education',
            ],
        },
        'higher-education-and-postsecondary': {
            'display_name': 'Higher Education and Postsecondary',
            'keywords': [
                'university', 'college', 'higher education', 'enrollment', 'graduation', 'tuition',
                'financial aid', 'faculty', 'student', 'academic', 'campus', 'degree', 'professor',
            ],
        },
        'learning-sciences-and-educational-psychology': {
            'display_name': 'Learning Sciences and Educational Psychology',
            'keywords': [
                'learning', 'motivation', 'self-efficacy', 'metacognition', 'student engagement',
                'academic achievement', 'learner', 'teaching', 'instruction',
                'cognitive development',
            ],
        },
        'sociology-and-social-context-of-education': {
            'display_name': 'Sociology and Social Context of Education',
            'keywords': [
                'educational stratification', 'educational attainment', 'racial achievement gap',
                'immigrant education', 'language minority education', 'bilingual education',
                'social foundations of education', 'cultural foundations of education',
                'critical race theory education', 'decolonial education', 'neighborhood education',
                'school desegregation', 'school integration', 'equity education',
                'race in education', 'gender in education', 'educational equity',
            ],
        },
        'special-education-and-disability-studies': {
            'display_name': 'Special Education and Disability Studies',
            'keywords': [
                'special education', 'learning disability', 'intellectual disability',
                'developmental disability education', 'emotional behavioral disorder',
                'autism education', 'autism spectrum education', 'IDEA', 'IEP',
                'individualized education program', 'inclusion education',
                'least restrictive environment', 'LRE', 'response to intervention', 'RTI',
                'multi-tiered system of supports', 'MTSS', 'assistive technology',
                'disability studies education',
            ],
        },
        'teaching-and-teacher-education': {
            'display_name': 'Teaching and Teacher Education',
            'keywords': [
                'pre-service teacher', 'teacher preparation', 'teacher education',
                'professional development teacher', 'classroom practice',
                'pedagogical content knowledge', 'PCK', 'teacher identity', 'teacher belief',
                'teacher agency', 'student teaching', 'mentoring teacher', 'teacher educator',
                'practitioner inquiry', 'teacher research', 'clinical practice teaching',
                'teaching practice', 'teacher learning', 'in-service teacher',
            ],
        },
    },
    'law': {
        'administrative-and-regulatory-law': {
            'display_name': 'Administrative and Regulatory Law',
            'keywords': [
                'regulation', 'deregulation', 'regulatory', 'compliance', 'enforcement',
                'rulemaking', 'administrative law', 'regulator', 'rule', 'law', 'legal requirement',
            ],
        },
        'civil-procedure-and-federal-courts': {
            'display_name': 'Civil Procedure and Federal Courts',
            'keywords': [
                'pleading', 'personal jurisdiction', 'Erie doctrine', 'class action',
                'aggregate litigation', 'federal court jurisdiction', 'habeas corpus',
                'abstention doctrine', 'conflict of laws', 'arbitration',
                'alternative dispute resolution', 'complex litigation', 'multidistrict litigation',
                'MDL', 'appellate procedure', 'remedies', 'declaratory judgment', 'injunction',
                'supplemental jurisdiction', 'removal jurisdiction',
            ],
        },
        'constitutional-law': {
            'display_name': 'Constitutional Law',
            'keywords': [
                'constitution', 'constitutional', 'judicial review', 'separation of powers',
                'federalism', 'bill of rights', 'due process', 'equal protection',
            ],
        },
        'contracts-and-commercial-law': {
            'display_name': 'Contracts and Commercial Law',
            'keywords': [
                'contract', 'breach', 'damages', 'performance', 'agreement', 'consideration',
                'promissory', 'commercial law',
            ],
        },
        'corporate-and-securities-law': {
            'display_name': 'Corporate and Securities Law',
            'keywords': [
                'corporate governance', 'fiduciary duty', 'business judgment rule',
                'mergers and acquisitions doctrine', 'securities regulation', 'Securities Act',
                'Exchange Act', 'SEC enforcement', 'private fund regulation', 'Chapter 11',
                'corporate bankruptcy', 'banking regulation', 'Dodd-Frank', 'board of directors',
                'shareholder litigation', 'derivative suit', 'proxy contest', 'insider trading',
                'Delaware corporate', 'corporate law theory',
            ],
        },
        'criminal-law-and-procedure': {
            'display_name': 'Criminal Law and Procedure',
            'keywords': [
                'crime', 'criminal', 'punishment', 'sentencing', 'prosecution', 'defendant',
                'incarceration', 'prison', 'police',
            ],
        },
        'empirical-legal-studies-and-law-and-economics': {
            'display_name': 'Empirical Legal Studies and Law and Economics',
            'keywords': [
                'empirical legal studies', 'regression discontinuity legal', 'RDD legal',
                'difference-in-differences legal', 'randomized legal experiment',
                'computational legal', 'NLP court opinion', 'judicial decisionmaking',
                'public choice law', 'behavioral law and economics empirical', 'court empirical',
                'judicial ideology', 'judge effect', 'court outcome regression',
                'legal data analytics', 'quantitative law', 'empirical court',
            ],
        },
        'environmental-and-energy-law': {
            'display_name': 'Environmental and Energy Law',
            'keywords': [
                'NEPA', 'environmental review', 'Clean Air Act law', 'Clean Water Act', 'CERCLA',
                'Endangered Species Act', 'climate regulation law', 'FERC', 'energy regulation law',
                'public utility law', 'renewable energy law', 'carbon market law',
                'international environmental law', 'natural resources law', 'public lands law',
                'water law', 'pollution control law', 'environmental justice law',
                'hazardous waste law',
            ],
        },
        'family-and-gender-law': {
            'display_name': 'Family and Gender Law',
            'keywords': [
                'marriage law', 'divorce law', 'child custody', 'adoption law',
                'assisted reproduction law', 'surrogacy', 'parentage law', 'domestic violence law',
                'child welfare law', 'juvenile dependency', 'LGBTQ rights law', 'Obergefell',
                'reproductive autonomy', 'Title IX', 'sex discrimination law', 'marital property',
                'alimony', 'prenuptial',
            ],
        },
        'health-law': {
            'display_name': 'Health Law',
            'keywords': [
                'FDA law', 'food and drug law', 'ACA law', 'Medicare law', 'Medicaid law',
                'public health law', 'emergency powers', 'vaccine mandate', 'bioethics',
                'reproductive health law', 'mental health law', 'disability law ADA', 'HIPAA',
                'health privacy', 'informed consent', 'end-of-life law', 'organ donation law',
                'abortion law', 'pharmaceutical regulation',
            ],
        },
        'intellectual-property-and-technology-law': {
            'display_name': 'Intellectual Property and Technology Law',
            'keywords': [
                'copyright', 'patent law', 'trademark', 'trade secret', 'right of publicity',
                'data protection law', 'privacy law', 'GDPR', 'cybersecurity law',
                'platform regulation law', 'AI law', 'internet governance',
                'telecommunications law', 'biotechnology law', 'fair use', 'patent infringement',
                'DMCA', 'trademark dilution', 'patentability', 'IP licensing',
            ],
        },
        'international-and-comparative-law': {
            'display_name': 'International and Comparative Law',
            'keywords': [
                'international law', 'treaty', 'customary law', 'jurisdiction', 'human rights law',
                'wto', 'international tribunal',
            ],
        },
        'labor-and-employment-law': {
            'display_name': 'Labor and Employment Law',
            'keywords': [
                'NLRA', 'collective bargaining law', 'labor union law', 'Title VII',
                'ADA discrimination', 'ADEA', 'employment discrimination', 'ERISA', 'FLSA', 'OSHA',
                'wage and hour', 'workplace safety law', 'employment arbitration', 'NLRB',
                'at-will employment', 'union election', 'hostile work environment', 'FMLA',
                'whistleblower', 'employment law',
            ],
        },
        'legal-theory-and-jurisprudence': {
            'display_name': 'Legal Theory and Jurisprudence',
            'keywords': [
                'jurisprudence', 'legal philosophy', 'natural law', 'positivism', 'legal realism',
                'rule of law', 'legal interpretation',
            ],
        },
        'property-law': {
            'display_name': 'Property Law',
            'keywords': [
                'real property', 'personal property', 'estate in land', 'takings', 'eminent domain',
                'just compensation', 'land use law', 'zoning law', 'trusts and estates',
                'water rights', 'landlord-tenant', 'lease law', 'fee simple', 'life estate',
                'easement', 'restrictive covenant', 'adverse possession', 'conveyance',
                'recording statute', 'mortgage law',
            ],
        },
        'tax-law': {
            'display_name': 'Tax Law',
            'keywords': [
                'federal income tax', 'corporate tax law', 'international tax', 'estate tax',
                'gift tax', 'state and local tax', 'SALT', 'tax procedure', 'tax controversy',
                'tax treaty', 'tax compliance', 'tax evasion law', 'Internal Revenue Code',
                'tax shelter', 'transfer pricing', 'FATCA', 'BEPS', 'tax planning', 'Tax Court',
                'tax policy law',
            ],
        },
        'torts': {
            'display_name': 'Torts',
            'keywords': [
                'negligence', 'intentional tort', 'strict liability', 'products liability',
                'defamation', 'libel', 'slander', 'privacy tort', 'nuisance', 'tort reform',
                'mass tort', 'medical malpractice doctrine', 'duty of care', 'foreseeability',
                'tort damages', 'comparative negligence', 'joint liability', 'tort causation',
                'premises liability', 'negligence per se',
            ],
        },
    },
    'political-science': {
        'american-institutions': {
            'display_name': 'American Political Institutions & Law',
            'keywords': [
                'congress', 'senate', 'house of representatives', 'presidential', 'executive order',
                'federal government', 'bureaucracy', 'agency', 'administrative state',
                'supreme court', 'judicial', 'constitutional', 'public law', 'federalism',
                'state legislature', 'governor', 'mayor', 'lawmaking', 'roll call', 'cosponsorship',
                'committee', 'separation of powers', 'redistricting', 'gerrymandering',
                'filibuster', 'legislator',
            ],
        },
        'comparative-political-economy': {
            'display_name': 'Comparative Political Economy & Development',
            'keywords': [
                'political economy', 'comparative political economy', 'welfare state',
                'social policy', 'redistribution', 'varieties of capitalism',
                'economic institutions', 'development', 'industrial policy', 'inequality',
                'taxation', 'fiscal policy', 'labor market institutions', 'unions',
                'economic growth', 'resource curse', 'distributive politics', 'poverty',
                'central bank',
            ],
        },
        'conflict-political-violence': {
            'display_name': 'Conflict, Violence & Contentious Politics',
            'keywords': [
                'civil war', 'armed conflict', 'insurgency', 'counterinsurgency', 'terrorism',
                'political violence', 'ethnic violence', 'communal violence', 'genocide',
                'mass atrocity', 'social movement', 'protest', 'riot', 'revolution', 'rebellion',
                'rebel governance', 'collective action', 'contentious politics', 'repression',
                'dissent',
            ],
        },
        'elections-public-opinion': {
            'display_name': 'Elections, Public Opinion & Voting Behavior',
            'keywords': [
                'election', 'voting', 'voter turnout', 'vote choice', 'public opinion',
                'political attitudes', 'partisanship', 'party identification', 'ideology',
                'campaign', 'campaign finance', 'political party', 'electoral system',
                'proportional representation', 'political communication', 'media effects',
                'interest group', 'lobbying', 'pac', 'participation', 'mobilization', 'ballot',
                'survey', 'primary election', 'midterm',
            ],
        },
        'identity-politics': {
            'display_name': 'Race, Ethnicity & Identity Politics',
            'keywords': [
                'race', 'ethnicity', 'racial politics', 'ethnic politics', 'minority politics',
                'identity', 'descriptive representation', 'substantive representation', 'gender',
                'women and politics', 'lgbtq', 'sexuality', 'immigration', 'immigrant',
                'citizenship', 'naturalization', 'group consciousness', 'linked fate',
                'intersectionality', 'discrimination', 'religion and politics', 'indigenous',
            ],
        },
        'international-organizations-law': {
            'display_name': 'International Organizations, Law & Global Governance',
            'keywords': [
                'international organization', 'intergovernmental organization', 'united nations',
                'imf', 'world bank', 'wto', 'international law', 'international court',
                'legalization', 'compliance', 'international regime', 'global governance',
                'human rights', 'international norms', 'norm diffusion', 'transnational advocacy',
                'global environmental governance', 'regional organization', 'cooperation', 'treaty',
            ],
        },
        'international-political-economy': {
            'display_name': 'International Political Economy',
            'keywords': [
                'international political economy', 'trade', 'trade policy', 'tariff',
                'international finance', 'monetary', 'exchange rate', 'capital flows',
                'foreign direct investment', 'fdi', 'multinational', 'globalization',
                'interdependence', 'sanctions', 'economic statecraft', 'sovereign debt',
                'financial crisis', 'regional integration', 'free trade agreement',
            ],
        },
        'international-security': {
            'display_name': 'International Security',
            'keywords': [
                'war', 'interstate war', 'militarized dispute', 'deterrence', 'coercion',
                'crisis bargaining', 'alliance', 'balance of power', 'military', 'strategy',
                'doctrine', 'nuclear', 'proliferation', 'arms control', 'grand strategy',
                'foreign policy', 'security', 'defense', 'intervention', 'hegemony',
                'security dilemma', 'signaling',
            ],
        },
        'political-methodology': {
            'display_name': 'Political Methodology & Formal Theory',
            'keywords': [
                'causal inference', 'regression discontinuity', 'difference-in-differences',
                'instrumental variable', 'matching', 'synthetic control', 'survey experiment',
                'text analysis', 'machine learning', 'bayesian', 'measurement',
                'item response theory', 'identification strategy', 'natural experiment',
                'quasi-experiment', 'game theory', 'formal model', 'social choice',
                'mechanism design', 'process tracing', 'qualitative methods', 'network analysis',
            ],
        },
        'political-psychology': {
            'display_name': 'Political Psychology',
            'keywords': [
                'political psychology', 'attitude', 'persuasion', 'motivated reasoning',
                'heuristics', 'emotion', 'affect', 'anxiety', 'anger', 'prejudice', 'stereotype',
                'intergroup', 'authoritarianism', 'personality', 'ideology', 'moral foundations',
                'framing', 'priming', 'polarization', 'political tolerance', 'cognition',
                'information processing',
            ],
        },
        'political-theory': {
            'display_name': 'Political Theory',
            'keywords': [
                'normative', 'justice', 'distributive justice', 'liberty', 'equality',
                'democratic theory', 'deliberative democracy', 'citizenship', 'legitimacy',
                'authority', 'political obligation', 'constitutional theory',
                'history of political thought', 'intellectual history', 'political thought',
                'canonical text', 'hobbes', 'locke', 'rousseau', 'machiavelli', 'aristotle', 'marx',
                'republicanism', 'conceptual history', 'cambridge school',
                'american political thought',
            ],
        },
        'regimes-democratization': {
            'display_name': 'Regimes, Democratization & Authoritarianism',
            'keywords': [
                'regime', 'democratization', 'democratic transition', 'consolidation',
                'backsliding', 'democratic erosion', 'authoritarianism', 'autocracy',
                'dictatorship', 'hybrid regime', 'competitive authoritarianism',
                'electoral authoritarianism', 'repression', 'co-optation', 'state capacity',
                'state formation', 'state-building', 'clientelism', 'patronage', 'corruption',
                'regime change', 'transition',
            ],
        },
    },
    'psychology': {
        'affective-psychology': {
            'display_name': 'Affective Science',
            'keywords': [
                'emotion regulation', 'affective science', 'mood', 'emotional experience',
                'emotion-cognition', 'interpersonal emotion', 'emotional development',
                'emotion expression', 'affective state', 'affect regulation',
                'emotional intelligence', 'emotion suppression', 'reappraisal', 'discrete emotion',
                'emotional response', 'affective forecasting', 'emotional reactivity',
            ],
        },
        'biological-neural-psychology': {
            'display_name': 'Biological and Neural Psychology',
            'keywords': [
                'behavioral neuroscience', 'biological psychology', 'cognitive neuroscience',
                'affective neuroscience', 'social neuroscience', 'neuropsychology',
                'comparative psychology', 'animal model', 'psychophysiology', 'psychopharmacology',
                'neuroimaging', 'fMRI', 'EEG', 'electrophysiology', 'lesion study',
                'brain-behavior', 'neural basis', 'computational neuroscience', 'brain mechanism',
            ],
        },
        'clinical-psychopathology': {
            'display_name': 'Clinical and Psychopathology',
            'keywords': [
                'depression', 'anxiety', 'therapy', 'psychotherapy', 'mental disorder', 'treatment',
                'ptsd', 'schizophrenia', 'diagnosis', 'intervention', 'disorder', 'mental health',
                'wellbeing', 'burnout', 'stress', 'trauma', 'substance', 'addiction',
            ],
        },
        'cognitive-psychology': {
            'display_name': 'Cognitive Psychology',
            'keywords': [
                'memory', 'attention', 'perception', 'reasoning', 'decision making',
                'problem solving', 'cognitive load', 'working memory', 'executive function',
                'cognitive', 'visual perception', 'inhibition', 'response time', 'reaction time',
                'priming', 'recognition',
            ],
        },
        'developmental-psychology': {
            'display_name': 'Developmental Psychology',
            'keywords': [
                'child development', 'adolescent', 'lifespan', 'attachment',
                'cognitive development', 'language acquisition', 'parenting',
            ],
        },
        'educational-learning-psychology': {
            'display_name': 'Educational and Learning Psychology',
            'keywords': [
                'learning', 'motivation', 'self-efficacy', 'metacognition', 'student engagement',
                'academic achievement', 'learner', 'teaching', 'instruction',
                'cognitive development',
            ],
        },
        'health-psychology': {
            'display_name': 'Health and Behavioral Medicine Psychology',
            'keywords': [
                'health behavior', 'behavior change', 'stress and coping', 'treatment adherence',
                'pain psychology', 'psychoneuroimmunology', 'behavioral medicine',
                'chronic illness', 'health disparity', 'well-being', 'sport psychology',
                'exercise psychology', 'smoking cessation', 'dietary behavior', 'physical activity',
                'health intervention', 'health belief', 'motivational interviewing',
                'biopsychosocial',
            ],
        },
        'industrial-organizational-psychology': {
            'display_name': 'Industrial, Organizational, and Work Psychology',
            'keywords': [
                'workplace', 'leadership', 'motivation', 'job satisfaction',
                'organizational behavior', 'team', 'employee', 'performance',
            ],
        },
        'quantitative-methods-psychology': {
            'display_name': 'Quantitative and Methodological Psychology',
            'keywords': [
                'psychometrics', 'test theory', 'classical test theory', 'item response theory',
                'IRT', 'factor analysis', 'confirmatory factor analysis',
                'structural equation modeling', 'SEM', 'multilevel modeling',
                'hierarchical linear model', 'longitudinal modeling', 'latent growth',
                'Bayesian psychology', 'meta-analysis', 'replicability', 'reproducibility',
                'scale validation', 'psychometric',
            ],
        },
        'social-personality-psychology': {
            'display_name': 'Social and Personality Psychology',
            'keywords': [
                'attitude', 'persuasion', 'conformity', 'group dynamics', 'stereotype', 'prejudice',
                'intergroup', 'social influence', 'self-concept',
            ],
        },
    },
    'public-policy': {
        'criminal-justice-policy': {
            'display_name': 'Criminal Justice, Drug, and Safety Policy',
            'keywords': [
                'mass incarceration', 'sentencing reform', 'policing reform', 'body camera',
                'use of force', 'consent decree', 'bail reform', 'pretrial reform',
                'community corrections', 'reentry policy', 'juvenile justice policy', 'drug policy',
                'drug decriminalization', 'marijuana legalization', 'gun policy', 'gun control',
                'cybercrime policy', 'surveillance policy', 'justice reinvestment',
                'criminal justice reform',
            ],
        },
        'education-policy': {
            'display_name': 'Education Policy',
            'keywords': [
                'No Child Left Behind', 'NCLB', 'ESSA', 'education accountability',
                'school choice policy', 'charter school policy', 'voucher policy',
                'teacher evaluation policy', 'value-added', 'school finance reform',
                'Pell Grant policy', 'student loan policy', 'pre-K policy', 'universal pre-K',
                'affirmative action', 'admissions policy', 'higher education regulation',
                'school reform', 'achievement gap', 'education accountability',
            ],
        },
        'environmental-energy-policy': {
            'display_name': 'Environmental, Energy, and Climate Policy',
            'keywords': [
                'Clean Air Act', 'EPA rulemaking', 'cap and trade', 'carbon tax', 'carbon pricing',
                'CBAM', 'renewable portfolio standard', 'RPS', 'clean energy policy',
                'energy efficiency program', 'climate adaptation', 'conservation policy',
                'public lands', 'EV incentive', 'electric vehicle policy',
                'environmental justice policy', 'climate policy', 'energy transition',
                'water policy',
            ],
        },
        'health-policy': {
            'display_name': 'Health Policy',
            'keywords': [
                'Medicare', 'Medicaid', 'Affordable Care Act', 'ACA', 'health insurance',
                'health coverage', 'insurance expansion', 'public health policy',
                'pandemic preparedness', 'opioid policy', 'tobacco policy', 'vaccine policy',
                'vaccination policy', 'pharmaceutical pricing', 'drug pricing', 'long-term care',
                'health equity policy', 'Medicaid expansion', 'single payer', 'health reform',
            ],
        },
        'policy-analysis-and-evaluation': {
            'display_name': 'Policy Analysis and Program Evaluation',
            'keywords': [
                'policy evaluation', 'cost-benefit', 'impact assessment', 'program evaluation',
                'evidence-based', 'policy design', 'implementation', 'policy', 'public policy',
                'government program', 'intervention',
            ],
        },
        'policy-process-theory': {
            'display_name': 'Policy Process and Policy Design Theory',
            'keywords': [
                'advocacy coalition framework', 'ACF', 'multiple streams framework', 'MSF',
                'punctuated equilibrium', 'PET', 'policy feedback', 'narrative policy framework',
                'NPF', 'policy diffusion', 'institutional analysis and development', 'IAD',
                'agenda setting', 'policy window', 'policy entrepreneur', 'policy design',
                'policy instrument', 'policy change', 'policy learning', 'epistemic community',
                'policy network', 'policy subsystem',
            ],
        },
        'public-management': {
            'display_name': 'Public Management and Administration',
            'keywords': [
                'bureaucracy', 'public management', 'civil service', 'government agency',
                'public sector', 'administrative reform', 'e-government', 'public service',
                'administration', 'government official',
            ],
        },
        'regulation-and-governance': {
            'display_name': 'Regulation and Governance',
            'keywords': [
                'regulation', 'deregulation', 'regulatory', 'compliance', 'enforcement',
                'rulemaking', 'administrative law', 'regulator', 'rule', 'law', 'legal requirement',
            ],
        },
        'science-technology-policy': {
            'display_name': 'Science, Technology, and Innovation Policy',
            'keywords': [
                'NIH funding', 'NSF funding', 'DARPA', 'federal R&D', 'industrial policy',
                'CHIPS Act', 'IRA', 'AI governance', 'AI policy', 'data privacy policy',
                'platform regulation', 'broadband policy', 'telecom policy', 'biotech policy',
                'biosecurity', 'space policy', 'emerging technology governance',
                'technology governance', 'innovation policy',
            ],
        },
        'security-and-foreign-policy': {
            'display_name': 'Defense, Security, and Foreign Policy',
            'keywords': [
                'defense budget', 'defense acquisition', 'military personnel', 'homeland security',
                'counterterrorism', 'cybersecurity policy', 'emergency management', 'FEMA',
                'intelligence reform', 'foreign aid', 'sanctions policy', 'refugee admission',
                'force structure', 'military readiness', 'national security policy',
                'defense policy', 'security cooperation', 'defense reform', 'DHS',
            ],
        },
        'social-welfare-and-poverty-policy': {
            'display_name': 'Social Welfare, Poverty, and Labor-Market Policy',
            'keywords': [
                'welfare state', 'social security', 'healthcare policy', 'education policy',
                'housing policy', 'poverty alleviation', 'social protection', 'social program',
                'benefit', 'assistance', 'aid',
            ],
        },
        'urban-housing-policy': {
            'display_name': 'Urban, Housing, and Community Development Policy',
            'keywords': [
                'zoning reform', 'YIMBY', 'inclusionary zoning', 'Section 8', 'public housing',
                'LIHTC', 'homelessness policy', 'CDBG', 'opportunity zone', 'place-based policy',
                'urban transit', 'congestion pricing', 'TOD', 'transit-oriented development',
                'local economic development', 'disaster recovery policy', 'gentrification policy',
                'displacement policy', 'housing affordability', 'fair housing',
            ],
        },
    },
    'sociology': {
        'crime-law-and-deviance': {
            'display_name': 'Crime, Law, and Deviance',
            'keywords': [
                'criminology', 'victimization', 'social control', 'sociology of law',
                'legal consciousness', 'mass incarceration', 'policing', 'prison',
                'criminal sentencing', 'drug use', 'substance use', 'juvenile delinquency',
                'white collar crime', 'neighborhood crime', 'recidivism',
                'criminal justice contact', 'punitive policy', 'decarceration', 'deviance',
            ],
        },
        'culture': {
            'display_name': 'Sociology of Culture, Meaning, and Media',
            'keywords': [
                'culture', 'identity', 'symbolic', 'meaning-making', 'ritual', 'boundary', 'taste',
                'cultural capital', 'habitus', 'cultural', 'norm', 'value', 'belief', 'ethnicity',
            ],
        },
        'economy-work-and-organizations': {
            'display_name': 'Economic Sociology, Work, and Organizations',
            'keywords': [
                'economic sociology', 'embeddedness', 'market sociology', 'social network analysis',
                'organizational field', 'labor market sociology', 'occupational structure',
                'profession', 'union', 'labor movement', 'work and family', 'workplace inequality',
                'gig work', 'precarious work', 'employment relations', 'sociology of work',
                'labor process', 'occupational mobility', 'valuation',
            ],
        },
        'family-and-life-course': {
            'display_name': 'Family, Childhood, and the Life Course',
            'keywords': [
                'marriage', 'cohabitation', 'divorce', 'parenting', 'parenthood', 'childhood',
                'adolescence', 'aging family', 'retirement', 'intergenerational transfer',
                'life course', 'kinship', 'family formation', 'single parent', 'stepfamily',
                'transition to adulthood', 'partnering', 'family complexity',
                'intergenerational relations', 'blended family',
            ],
        },
        'gender-and-sexuality': {
            'display_name': 'Gender and Sexuality',
            'keywords': [
                'gender inequality', 'masculinities', 'gender at work', 'sexual identity', 'LGBTQ',
                'queer', 'reproductive politics', 'gender pay gap', 'gender discrimination',
                'gender role', 'transgender', 'feminist sociology', 'intersectional',
                'sexual orientation', 'gender and family', 'gendered division of labor',
                'sexuality studies', 'gender identity', 'gender and state', 'feminist theory',
            ],
        },
        'global-development-and-political-economy': {
            'display_name': 'Global and Transnational Sociology, Development',
            'keywords': [
                'world system', 'comparative historical', 'transnational', 'globalization',
                'global inequality', 'postcolonial sociology', 'varieties of capitalism',
                'dependency theory', 'global value chain', 'neoliberalism', 'structural adjustment',
                'IMF', 'World Bank', 'transnational institution', 'global governance', 'decolonial',
                'north-south', 'global capitalism', 'development trajectory',
            ],
        },
        'health-medicine-and-body': {
            'display_name': 'Medical Sociology, Health, and the Body',
            'keywords': [
                'health disparities', 'illness', 'healthcare', 'medicalization', 'patient',
                'disability', 'mental health', 'chronic disease',
            ],
        },
        'political-sociology-and-the-state': {
            'display_name': 'Political Sociology, the State, and Social Movements',
            'keywords': [
                'political sociology', 'state capacity', 'state formation', 'regime change',
                'democratization', 'contentious politics', 'social movement', 'protest',
                'collective action', 'revolution', 'civil conflict', 'human rights', 'nationalism',
                'citizenship rights', 'repression', 'mobilization', 'political opportunity',
                'framing process', 'resource mobilization', 'state power',
            ],
        },
        'population-and-demography': {
            'display_name': 'Population and Demography',
            'keywords': [
                'fertility', 'mortality', 'life expectancy', 'longevity', 'demographic',
                'demographic transition', 'population aging', 'age structure', 'internal migration',
                'international migration', 'migration flow', 'population composition',
                'vital statistic', 'demographic projection', 'total fertility rate',
                'period fertility', 'mortality differential', 'demographic estimation',
                'population health', 'demographic method',
            ],
        },
        'race-ethnicity-and-migration': {
            'display_name': 'Race, Ethnicity, and Migration',
            'keywords': [
                'racial formation', 'racial boundary', 'ethnic boundary', 'immigrant assimilation',
                'immigrant incorporation', 'second generation', 'racial discrimination',
                'transnationalism', 'diaspora', 'ethnic enclave', 'indigenous',
                'citizenship belonging', 'deservingness', 'refugee', 'border regime',
                'racialization', 'racial classification', 'immigrant integration', 'panethnicity',
                'racial inequality',
            ],
        },
        'religion': {
            'display_name': 'Sociology of Religion',
            'keywords': [
                'congregation', 'religious identity', 'secularization', 'nonreligion',
                'religious movement', 'new religious movement', 'religion and politics',
                'religious pluralism', 'spirituality', 'religion and family', 'evangelical',
                'megachurch', 'religious belonging', 'religious participation', 'faith-based',
                'lived religion', 'religious authority', 'religious ritual', 'religious tradition',
            ],
        },
        'science-technology-and-knowledge': {
            'display_name': 'Science, Technology, and Knowledge',
            'keywords': [
                'sociology of science', 'sociology of knowledge', 'expertise',
                'scientific community', 'scientific controversy', 'digital platform',
                'algorithmic system', 'sociotechnical', 'infrastructure studies', 'quantification',
                'science and technology studies', 'STS', 'classification practice',
                'standardization', 'knowledge production', 'lab study', 'scientific work',
                'data infrastructure', 'big data',
            ],
        },
        'sociology-of-education-soc': {
            'display_name': 'Sociology of Education',
            'keywords': [
                'educational attainment', 'school', 'college', 'tracking', 'achievement gap',
                'dropout', 'teacher', 'curriculum',
            ],
        },
        'stratification-and-inequality': {
            'display_name': 'Stratification, Inequality, and Mobility',
            'keywords': [
                'inequality', 'social mobility', 'class', 'socioeconomic status',
                'intergenerational', 'wealth gap', 'income distribution', 'poverty', 'racial',
                'gender gap', 'disparity', 'equity', 'stratification',
            ],
        },
        'theory-and-methods-soc': {
            'display_name': 'Sociological Theory and Methods',
            'keywords': [
                'sociological theory', 'classical sociology', 'social theory',
                'mathematical sociology', 'ethnomethodology', 'conversation analysis',
                'history of sociology', 'agent-based modeling', 'formal theory sociology',
                'theoretical sociology', 'methodological innovation sociology',
                'computational sociology', 'sociological method', 'sociology methodology',
                'measurement sociology', 'social psychology sociology', 'scaling method',
            ],
        },
        'urban-community-and-environment': {
            'display_name': 'Urban, Community, and Environmental Sociology',
            'keywords': [
                'urban', 'city', 'neighborhood', 'gentrification', 'segregation', 'housing',
                'community', 'metropolitan',
            ],
        },
    },
}
